### ISSUE TITLE
Intel Core 2 Duo seems unsupported

### ISSUE THREAD

**Issue by awsom82** [golangci/golangci-lint#1001]
Thank you for creating the issue!

- [+] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [+] Yes, I've searched similar issues on GitHub and didn't find any.
- [+] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
√
PC=0x1066c50 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/preempt_amd64.s:8 fp=0xc000104e00 sp=0xc000104df8 pc=0x1066c50
math/rand.seedrand(...)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/math/rand/rng.go:195
math/rand.(*rngSource).Seed(0xc000110000, 0x1)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/math/rand/rng.go:218 +0x8b fp=0xc000104e08 sp=0xc000104e00 pc=0x110bfbb
math/rand.NewSource(0x1, 0xc000040178, 0xc000104e58)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/math/rand/rand.go:46 +0x4a fp=0xc000104e30 sp=0xc000104e08 pc=0x110ac3a
math/rand.init()
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/math/rand/rand.go:293 +0x2e fp=0xc000104e68 sp=0xc000104e30 pc=0x110c20e
runtime.doInit(0x23081c0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5414 +0x8a fp=0xc000104e98 sp=0xc000104e68 pc=0x104233a
runtime.doInit(0x2310f20)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc000104ec8 sp=0xc000104e98 pc=0x1042307
runtime.doInit(0x2310400)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc000104ef8 sp=0xc000104ec8 pc=0x1042307
runtime.doInit(0x230fe60)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc000104f28 sp=0xc000104ef8 pc=0x1042307
runtime.doInit(0x23150c0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc000104f58 sp=0xc000104f28 pc=0x1042307
runtime.doInit(0x2309ac0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc000104f88 sp=0xc000104f58 pc=0x1042307
runtime.main()
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:190 +0x1ce fp=0xc000104fe0 sp=0xc000104f88 pc=0x103578e
runtime.goexit()
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000104fe8 sp=0xc000104fe0 pc=0x10653d1

rax    0x75
rbx    0x7eab
rcx    0xc000110000
rdx    0x55fd03bf
rdi    0xf4aff05cca9d03bf
rsi    0x55fd03bf
rbp    0xc000104e20
rsp    0xc000104df8
r8     0x5e95c9f600000
r9     0x1
r10    0xc000110000
r11    0x1
r12    0x1
r13    0x40
r14    0x3
r15    0x55
rip    0x1066c50
rflags 0x10213
cs     0x2b
fs     0x0
gs     0x0

```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.13.9 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/awsom82/go/bin"
GOCACHE="/Users/awsom82/Library/Caches/go-build"
GOENV="/Users/awsom82/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/awsom82/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go@1.13/1.13.9/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.13/1.13.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/awsom82/Sites/sendtips/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4h/b1jdkstx2hx7lfq0k9x87v580000gn/T/go-build598402962=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint run -v
SIGILL: illegal instruction
PC=0x1066c50 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/preempt_amd64.s:8 fp=0xc0000db858 sp=0xc0000db850 pc=0x1066c50
compress/flate.(*decompressor).huffmanBlock(0xc00023ec00)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/compress/flate/inflate.go:605 +0x55 fp=0xc0000db8e0 sp=0xc0000db858 pc=0x1324815
compress/flate.(*decompressor).Read(0xc00023ec00, 0xc000488000, 0x37e00, 0x37e00, 0x3fe00, 0x85a6b1b3, 0x0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/compress/flate/inflate.go:347 +0x77 fp=0xc0000db918 sp=0xc0000db8e0 pc=0x1323e17
compress/gzip.(*Reader).Read(0xc000248b00, 0xc000488000, 0x37e00, 0x37e00, 0x8000, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/compress/gzip/gunzip.go:251 +0x87 fp=0xc0000db9b8 sp=0xc0000db918 pc=0x1328787
bytes.(*Buffer).ReadFrom(0xc000031c80, 0x1cd88a0, 0xc000248b00, 0x2fb1050, 0xc000031c80, 0xc000113a01)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/bytes/buffer.go:204 +0xb1 fp=0xc0000dba28 sp=0xc0000db9b8 pc=0x10fae51
io.copyBuffer(0x1cd8800, 0xc000031c80, 0x1cd88a0, 0xc000248b00, 0x0, 0x0, 0x0, 0xc00022eac0, 0xc000113bf8, 0x38)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/io/io.go:391 +0x2fc fp=0xc0000dbaa0 sp=0xc0000dba28 pc=0x10ab50c
io.Copy(...)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/io/io.go:364
github.com/nbutton23/zxcvbn-go/data.bindataRead(0x2353320, 0x214e5, 0x214e5, 0x1b5c94f, 0x11, 0xc000360000, 0x10f1cf4, 0x1b5c94f, 0x11, 0x1002c61)
	/home/travis/gopath/pkg/mod/github.com/nbutton23/zxcvbn-go@v0.0.0-20180912185939-ae427f1e4c1d/data/bindata.go:36 +0x1eb fp=0xc0000dbb50 sp=0xc0000dbaa0 pc=0x171745b
github.com/nbutton23/zxcvbn-go/data.dataEnglishJsonBytes(...)
	/home/travis/gopath/pkg/mod/github.com/nbutton23/zxcvbn-go@v0.0.0-20180912185939-ae427f1e4c1d/data/bindata.go:103
github.com/nbutton23/zxcvbn-go/data.dataEnglishJson(0x19c2dc0, 0xc000031170, 0x1b5c94f)
	/home/travis/gopath/pkg/mod/github.com/nbutton23/zxcvbn-go@v0.0.0-20180912185939-ae427f1e4c1d/data/bindata.go:110 +0x6c fp=0xc0000dbc40 sp=0xc0000dbb50 pc=0x171798c
github.com/nbutton23/zxcvbn-go/data.Asset(0x1b5c94f, 0x11, 0xc000360000, 0x60c7d, 0x7fe00, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/nbutton23/zxcvbn-go@v0.0.0-20180912185939-ae427f1e4c1d/data/bindata.go:286 +0xc8 fp=0xc0000dbcd8 sp=0xc0000dbc40 pc=0x1718e28
github.com/nbutton23/zxcvbn-go/frequency.getAsset(...)
	/home/travis/gopath/pkg/mod/github.com/nbutton23/zxcvbn-go@v0.0.0-20180912185939-ae427f1e4c1d/frequency/frequency.go:34
github.com/nbutton23/zxcvbn-go/frequency.init.0()
	/home/travis/gopath/pkg/mod/github.com/nbutton23/zxcvbn-go@v0.0.0-20180912185939-ae427f1e4c1d/frequency/frequency.go:23 +0x123 fp=0xc0000dbdd8 sp=0xc0000dbcd8 pc=0x171c023
runtime.doInit(0x23097c0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5414 +0x8a fp=0xc0000dbe08 sp=0xc0000dbdd8 pc=0x104233a
runtime.doInit(0x230d4c0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbe38 sp=0xc0000dbe08 pc=0x1042307
runtime.doInit(0x2308e00)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbe68 sp=0xc0000dbe38 pc=0x1042307
runtime.doInit(0x230c8c0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbe98 sp=0xc0000dbe68 pc=0x1042307
runtime.doInit(0x231a2a0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbec8 sp=0xc0000dbe98 pc=0x1042307
runtime.doInit(0x230e9a0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbef8 sp=0xc0000dbec8 pc=0x1042307
runtime.doInit(0x2312420)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbf28 sp=0xc0000dbef8 pc=0x1042307
runtime.doInit(0x23150c0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbf58 sp=0xc0000dbf28 pc=0x1042307
runtime.doInit(0x2309ac0)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:5409 +0x57 fp=0xc0000dbf88 sp=0xc0000dbf58 pc=0x1042307
runtime.main()
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:190 +0x1ce fp=0xc0000dbfe0 sp=0xc0000dbf88 pc=0x103578e
runtime.goexit()
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000dbfe8 sp=0xc0000dbfe0 pc=0x10653d1

rax    0x0
rbx    0xc00023ec00
rcx    0xa
rdx    0x14
rdi    0xa
rsi    0x4a8
rbp    0xc0000db8d0
rsp    0xc0000db850
r8     0x7
r9     0x8000
r10    0xa
r11    0xa7
r12    0xffffffffffffffff
r13    0x200
r14    0x2
r15    0x2
rip    0x1066c50
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
```

</details>

**Comment by awsom82** [comment]
Looks like Go v1.14 drop support for Intel Core 2 Duo.
