### ISSUE TITLE
Inreproducable panic

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#214]
```
Got golangci-lint warnings: []report.Warning{report.Warning{Tag:"runner", Text:"Panic stack trace: goroutine 2271 [running]:\nruntime/debug.Stack(0xcdceba, 0x12, 0xc01298d1f8)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe.func1(0xc01298db48, 0xc016e79b00, 0xc, 0xc, 0xe0a4e0, 0xc019935020)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:76 +0xb7\npanic(0xb92c00, 0x13e18b0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).function(0xc01298d618, 0xc025d22b40)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:57 +0xf2\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).function(0xc01298d618, 0xc025d22a00)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:60 +0x14d\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).function(0xc01298d618, 0xc025d13180)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:60 +0x14d\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).program(0xc01298d618)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:40 +0xa1\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.AllFunctions(0xc0254bc820, 0xc01298d6e0)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:27 +0x4b\ngithub.com/golangci/golangci-lint/vendor/mvdan.cc/interfacer/check.(*Checker).Check(0xc026807f80, 0xc026807f80, 0xc0285cbed0, 0xc01298d830, 0x40b6b8, 0xc1fae0)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/mvdan.cc/interfacer/check/check.go:143 +0x150\ngithub.com/golangci/golangci-lint/pkg/golinters.Interfacer.Run(0xe05c20, 0xc0001f9f80, 0xc026807e60, 0xc00a1a8880, 0xc95ec2, 0xa, 0xc000041a40, 0xc0000427a0)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/golinters/interfacer.go:27 +0x81\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe(0xc016e79b00, 0xc, 0xc, 0xe0a4e0, 0xc019935020, 0xe05c20, 0xc0001f9f80, 0xc006908f00, 0xe04c60, 0x150e038, ...)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:82 +0x1ab\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runWorker.func1()\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:116 +0xd6\ngithub.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc00e3e06e0, 0xc95ec2, 0xa, 0xc01298de40)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:75 +0x50\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runWorker(0xc016e79b00, 0xc, 0xc, 0xe0a4e0, 0xc019935020, 0xe05c20, 0xc0001f9f80, 0xc006908f00, 0xc0069091a0, 0xc006909260, ...)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:115 +0x20a\ngithub.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers.func1(0xc0263b51d0, 0xc019935500, 0xe05c20, 0xc0001f9f80, 0xc006908f00, 0xc0069091a0, 0xc006909260, 0xc0069092c0, 0x4, 0x4, ...)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:170 +0x13b\ncreated by github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:167 +0x1b8\n"}, report.Warning{Tag:"runner", Text:"Can't run linter interfacer: panic occurred: runtime error: invalid memory address or nil pointer dereference"}}
```

Can't reproduce it, started after rearranging forks and using go1.11.

**Comment by jirfag** [comment]
continue in https://github.com/golangci/golangci-lint/issues/277
