### ISSUE TITLE
Go 1.17 panic 

### ISSUE THREAD

**Issue by pauwlsky** [golangci/golangci-lint#2197]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

After upgrading to Go 1.17 I can no longer run any `golangci-lint` commands without hitting this panic:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20478c9e]
```

The panic occurs running any `golangci-lint` command, and occurs from  v1.32.0 up until v1.41.0 (where it goes away).
The pinned version we are using for our project is v1.32.0. We are using go modules an `golangci-lint` is installed via `go install` or `go get`. 

Note, this problem does not occur when downgrading to Go 1.16. 

### Version of golangci-lint

<details>

```
1.32.0
```

</details>

### Configuration file

<details>

```ml
linters:
  disable-all: true
  fast: false
  enable:
    # Enabled-by-default set
    - govet
#    - errcheck # don't use; pedantically requires checking of errors from deferred functions, which is a pain to do all over the place
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

    # Disabled-by-default set
    - depguard
    - dogsled
#    - bodyclose # don't use; it doesn't handle delegating the resp.Close() call to another function, which we do often via drainAndClose
#    - dupl
    - funlen
#    - gochecknoinits # don't use; we have several existing init() functions doing important stuff
    - goconst
    - gocritic
    - gocyclo
    - gocognit
    - gofmt
#    - goimports # don't use; too finnicky
#    - golint # don't use; designed to be advisory and too loose for use as a strict checker
    - gosec
    - interfacer
#    - lll # don't use; we have way too many violations to fuss with, and no one's eager to draw a line on this.
    - misspell
    - nakedret
    - scopelint
#    - stylecheck # don't use; too opinionated and lacking docs on how to configure
    - unconvert
    - unparam
    - whitespace
#    - wsl # don't use; huge number of existing failures on very opinionated whitespace checks
#    - godox # detects TODO/BUG/FIXME comments, which we have a fair number of. Maybe useful in advisory fashion, or if we decide to clean them all up.
#    - maligned # don't use; fiddly micro-optimization
#    - prealloc # don't use; too pedantic, fiddly micro-optimization
#    - gochecknoglobals # don't use; too strict

# options for analysis running
run:
  # default concurrency is a available CPU number
  #concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 20m # 1m gets timeouts on TeamCity agents, so give it plenty of wiggle room.

  # exit code when at least one issue was found, default is 1
  #issues-exit-code: 1

  # include test files or not, default is true
  #tests: true

  # list of build tags, all linters use it. Default is empty list.
  #build-tags:
  #  - mytag

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - vendor

  # which files to skip: they will be analyzed, but issues from them
  # won't be reported. Default value is empty list, but there is
  # no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
  #skip-files:
  #  - ".*\\.my\\.go$"
  #  - lib/bad.go

  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #modules-download-mode: readonly|release|vendor


# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  #format: colored-line-number

  # print lines of code with issue, default is true
  #print-issued-lines: true

  # print linter name in the end of issue text, default is true
  #print-linter-name: true


# all available settings of specific linters
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      #- github.com/sirupsen/logrus
    packages-with-error-messages:
      # specify an error message to output when a blacklisted package is used
      #github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  dogsled:
    # checks assignments with too many blank identifiers; default is 2
    #max-blank-identifiers: 2

#  errcheck:
#    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
#    # default is false: such cases aren't reported by default.
#   # check-type-assertions: false
#
#    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
#    # default is false: such cases aren't reported by default.
#    #check-blank: false
#
#    # [deprecated] comma-separated list of pairs of the form pkg:regex
#    # the regex is used to ignore names within pkg. (default "fmt:.*").
#    # see https://github.com/kisielk/errcheck#the-deprecated-method for details
#    #ignore: fmt:.*,io/ioutil:^Read.*
#
#    # path to a file containing a list of functions to exclude from checking
#    # see https://github.com/kisielk/errcheck#excluding-functions for details
#    #exclude: /path/to/file.txt
#
  funlen:
    # These are set at the current high water marks. They should be reduced to more stringent values
    # as refactoring is done.
    lines: 344
    statements: 240
#
  govet:
    # settings per analyzer
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    # enable or disable analyzers by name
    enable:
      - asmdecl
      - assign
      - atomicalign
      - bools
      - buildssa
      - buildtag
      - cgocall
      - composite
      - copylock
      - ctrlflow
      - errorsas
      - findcall
      - httpresponse
      - inspect
      - loopclosure
      - lostcancel
      - nilfunc
      - pkgfact
      - printf
      - shift
      - sortslice
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - deepequalerrors # would like to enable this, but need to first update a number of tests to use testutil.ErrorSpec
      - shadow # we'd like to avoid shadowing in general, but pragmatically there's a need for a carve-out for vars named "err" and this doesn't seem to offer that
#  golint:
#    # minimal confidence for issues, default is 0.8
#    #min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
#  goimports:
#    # put imports beginning with prefix after 3rd-party packages;
#    # it's a comma-separated list of prefixes
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 35 # current high water mark; reduce as possible
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 51 # current high water mark; reduce as possible
#  maligned:
#    # print struct with more effective memory layout or not, false by default
#    suggest-new: true
#  dupl:
#    # tokens count to trigger issue, 150 by default
#    threshold: 100
  goconst:
    # minimal length of string constant, 3 by default
    #min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 6
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - analyses # false positive
#  lll:
#    # max line length, lines longer will be reported. Default is 120.
#    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
#    #line-length: 120
#    # tab width in spaces. Default to 1.
#    #tab-width: 1
  unused:
    # treat code as a program (not a library) and report unused exported identifiers; default is false.
    # XXX: if you enable this setting, unused will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find funcs usages. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    #check-exported: false
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    #check-exported: false
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 30
#  prealloc:
#    # XXX: we don't recommend using this linter before doing performance profiling.
#    # For most programs usage of prealloc will be a premature optimization.
#
#    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
#    # True by default.
#    #simple: true
#    #range-loops: true # Report preallocation suggestions on range loops, true by default
#    #for-loops: false # Report preallocation suggestions on for loops, false by default
  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    enabled-checks:
      # DIAGNOSTIC
      # Enabled by default
      - appendAssign
      - caseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - flagDeref
      # Disabled by default
      - argOrder
      - badCond
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      #- exitAfterDefer
      - flagName
      - nilValReturn
      - octalLiteral
      - offBy1
      - sloppyReassign
      - weakCond

      # STYLE
      # Enabled by default
      - assignOp
      - captLocal
      - defaultCaseOrder
      - elseif
      - ifElseChain
      - regexpMust
      #- singleCaseSwitch # don't enable; we do these in a few spots and it feels appropriate to indicate intent
      - sloppyLen
      - switchTrue
      - typeSwitchVar
      - underef
      - unlambda
      - unslice
      # Disabled by default
      - boolExprSimplify
      - builtinShadow
      - commentFormatting
      - commentedOutImport
      - docStub
      #- emptyFallthrough # don't enable; doesn't handle fallthrough to "default" correctly.
      - emptyStringTest
      - hexLiteral
      - importShadow
      - initClause
      - methodExprCall
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - stringXbytes
      #- typeAssertChain
      - typeUnparen
      - unlabelStmt
      - unnamedResult
      - unnecessaryBlock
      - valSwap
      #- wrapperFunc # don't enable until we're on a version of Go that offers strings.ReplaceAll (that's mostly what this finds)
      - yodaStyleExpr

      # PERF
      # Disabled by default
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy

    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint` run to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    #enabled-tags:
    #  - performance

    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      hugeParam:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 512
#  godox:
#    # report any comments starting with keywords, this is useful for TODO or FIXME comments that
#    # might be left in the code accidentally and should be resolved before merging
#    keywords: # default keywords are TODO, BUG, and FIXME, these can be overwritten by this setting
#      #- NOTE
#      #- OPTIMIZE # marks code that should be optimized before merging
#      #- HACK # marks hack-arounds that should be removed before merging
#
  whitespace:
    multi-if: false
#  wsl:
#    # If true append is only allowed to be cuddled if appending value is
#    # matching variables, fields or types on line above. Default is true.
#    strict-append: true
#    # Allow calls and assignments to be cuddled as long as the lines have any
#    # matching variables, fields or types. Default is true.
#    allow-assign-and-call: true
#    # Allow multiline assignments to be cuddled. Default is true.
#    allow-multiline-assign: true

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude:
    #- abcdef

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - scopelint

    # Exclude known linters from partially hard-vendored code,
    # which is impossible to exclude via "nolint" comments.
    #- path: internal/hmac/
    #  text: "weak cryptographic primitive"
    #  linters:
    #    - gosec

    # Exclude some staticcheck messages
    #- linters:
    #    - staticcheck
    #  text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    #- linters:
    #    - lll
    #  source: "^//go:generate "

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing
  # large codebase. It's not practical to fix all existing issues at the moment
  # of integration: much better don't allow issues in new code.
  # Default is false.
  #new: false

  # Show only new issues created after git revision `REV`
  #new-from-rev: REV

  # Show only new issues created in git patch with set file path.
  #new-from-patch: path/to/patch/file
```

</details>

### Go environment

<details>

```
go version go1.17 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kwells/Library/Caches/go-build"
GOENV="/Users/kwells/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kwells/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kwells/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kwells/radar/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l_/6_gxy04j2v9_r7n5tcrn2xqr0000gp/T/go-build2836680716=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

The panic occurs running any `golangci-lint` command, and occurs from  v1.32.0 up until v1.41.0
The pinned version we are using for our project is v1.32.0

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20478c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20478c9e
stack: frame={sp:0x7ffeefbff6c8, fp:0x7ffeefbff718} stack=[0x7ffeefb80768,0x7ffeefbff7d0)
0x00007ffeefbff5c8:  0x01007ffeefbff5e8  0x0000000000000004
0x00007ffeefbff5d8:  0x000000000000001f  0x00007fff20478c9e
0x00007ffeefbff5e8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff5f8:  0x0000000004036391 <runtime.throw+0x0000000000000071>  0x00007ffeefbff698
0x00007ffeefbff608:  0x0000000004a1e945  0x00007ffeefbff650
0x00007ffeefbff618:  0x0000000004036648 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000522ef60
0x00007ffeefbff628:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff638:  0x00007ffeefbff698  0x0000000004036391 <runtime.throw+0x0000000000000071>
0x00007ffeefbff648:  0x000000000522ef60  0x00007ffeefbff688
0x00007ffeefbff658:  0x00000000040365d0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff668
0x00007ffeefbff668:  0x0000000004036600 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000522ef60
0x00007ffeefbff678:  0x0000000004036391 <runtime.throw+0x0000000000000071>  0x00007ffeefbff698
0x00007ffeefbff688:  0x00007ffeefbff6b8  0x0000000004036391 <runtime.throw+0x0000000000000071>
0x00007ffeefbff698:  0x00007ffeefbff6a0  0x00000000040363c0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff6a8:  0x0000000004a2cb4b  0x000000000000002a
0x00007ffeefbff6b8:  0x00007ffeefbff708  0x000000000404c876 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff6c8: <0x0000000004a2cb4b  0x000000000522ef60
0x00007ffeefbff6d8:  0x00007ffeefbff748  0x0000000004028386 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff6e8:  0x000000c000198000  0x0000000000002000
0x00007ffeefbff6f8:  0x000000c000000008  0x0000000000000000
0x00007ffeefbff708:  0x00007ffeefbff750 !0x00007fff20478c9e
0x00007ffeefbff718: >0x00007ffeefbff750  0x000000000508f000
0x00007ffeefbff728:  0x000000000000035c  0x00000000042a6285 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff738:  0x000000000406b97f <runtime.syscall+0x000000000000001f>  0x000000c000197848
0x00007ffeefbff748:  0x00007ffeefbff790  0x000000c000197818
0x00007ffeefbff758:  0x00000000040697b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff768:  0x0000000004003f00 <internal/bytealg.Index+0x0000000000000000>  0x3f00000000001018
0x00007ffeefbff778:  0x0000000000000000  0x000000000526ceb8
0x00007ffeefbff788:  0x0000000000000810  0x000000c0000001a0
0x00007ffeefbff798:  0x00000000040678c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff7a8:  0x0000000004b36d28  0x000000000522ef60
0x00007ffeefbff7b8:  0x00007ffeefbff800  0x00000000040677c5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff7c8:  0x000000000406777d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x4a2cb4b, 0x522ef60})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20478c9e
stack: frame={sp:0x7ffeefbff6c8, fp:0x7ffeefbff718} stack=[0x7ffeefb80768,0x7ffeefbff7d0)
0x00007ffeefbff5c8:  0x01007ffeefbff5e8  0x0000000000000004
0x00007ffeefbff5d8:  0x000000000000001f  0x00007fff20478c9e
0x00007ffeefbff5e8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff5f8:  0x0000000004036391 <runtime.throw+0x0000000000000071>  0x00007ffeefbff698
0x00007ffeefbff608:  0x0000000004a1e945  0x00007ffeefbff650
0x00007ffeefbff618:  0x0000000004036648 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000522ef60
0x00007ffeefbff628:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff638:  0x00007ffeefbff698  0x0000000004036391 <runtime.throw+0x0000000000000071>
0x00007ffeefbff648:  0x000000000522ef60  0x00007ffeefbff688
0x00007ffeefbff658:  0x00000000040365d0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff668
0x00007ffeefbff668:  0x0000000004036600 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000522ef60
0x00007ffeefbff678:  0x0000000004036391 <runtime.throw+0x0000000000000071>  0x00007ffeefbff698
0x00007ffeefbff688:  0x00007ffeefbff6b8  0x0000000004036391 <runtime.throw+0x0000000000000071>
0x00007ffeefbff698:  0x00007ffeefbff6a0  0x00000000040363c0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff6a8:  0x0000000004a2cb4b  0x000000000000002a
0x00007ffeefbff6b8:  0x00007ffeefbff708  0x000000000404c876 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff6c8: <0x0000000004a2cb4b  0x000000000522ef60
0x00007ffeefbff6d8:  0x00007ffeefbff748  0x0000000004028386 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff6e8:  0x000000c000198000  0x0000000000002000
0x00007ffeefbff6f8:  0x000000c000000008  0x0000000000000000
0x00007ffeefbff708:  0x00007ffeefbff750 !0x00007fff20478c9e
0x00007ffeefbff718: >0x00007ffeefbff750  0x000000000508f000
0x00007ffeefbff728:  0x000000000000035c  0x00000000042a6285 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff738:  0x000000000406b97f <runtime.syscall+0x000000000000001f>  0x000000c000197848
0x00007ffeefbff748:  0x00007ffeefbff790  0x000000c000197818
0x00007ffeefbff758:  0x00000000040697b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff768:  0x0000000004003f00 <internal/bytealg.Index+0x0000000000000000>  0x3f00000000001018
0x00007ffeefbff778:  0x0000000000000000  0x000000000526ceb8
0x00007ffeefbff788:  0x0000000000000810  0x000000c0000001a0
0x00007ffeefbff798:  0x00000000040678c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff7a8:  0x0000000004b36d28  0x000000000522ef60
0x00007ffeefbff7b8:  0x00007ffeefbff800  0x00000000040677c5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff7c8:  0x000000000406777d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x42a6280, 0x1, 0x40487413, 0xc0001978d8)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000197848 sp=0xc000197828 pc=0x406637b
syscall.syscall(0x40b74c6, 0xa4d1090, 0xc000197900, 0x40b73f8)
	<autogenerated>:1 +0x26 fp=0xc000197890 sp=0xc000197848 pc=0x406c146
golang.org/x/sys/unix.ioctl(0x4987ab8, 0x4, 0x1000000076900)
	/Users/kwells/go/pkg/mod/golang.org/x/sys@v0.0.0-20210423082822-04245dca01da/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc0001978c0 sp=0xc000197890 pc=0x42a5b79
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/kwells/go/pkg/mod/golang.org/x/sys@v0.0.0-20210423082822-04245dca01da/unix/ioctl.go:73
github.com/mattn/go-isatty.IsTerminal(0x4987ab8)
	/Users/kwells/go/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc000197930 sp=0xc0001978c0 pc=0x42a6390
github.com/fatih/color.init()
	/Users/kwells/go/pkg/mod/github.com/fatih/color@v1.9.0/color.go:21 +0x7a fp=0xc000197968 sp=0xc000197930 pc=0x42a88da
runtime.doInit(0x5097360)
	/usr/local/go/src/runtime/proc.go:6498 +0x123 fp=0xc000197aa0 sp=0xc000197968 pc=0x4045e23
runtime.doInit(0x5097480)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc000197bd8 sp=0xc000197aa0 pc=0x4045d71
runtime.doInit(0x5096520)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc000197d10 sp=0xc000197bd8 pc=0x4045d71
runtime.doInit(0x509f680)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc000197e48 sp=0xc000197d10 pc=0x4045d71
runtime.doInit(0x5093a40)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc000197f80 sp=0xc000197e48 pc=0x4045d71
runtime.main()
	/usr/local/go/src/runtime/proc.go:238 +0x1e6 fp=0xc000197fe0 sp=0xc000197f80 pc=0x4038ca6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000197fe8 sp=0xc000197fe0 pc=0x4069aa1```
```

</details>

### Code example or link to a public repository

<details>

The repository is not public.

</details>

**Comment by ldez** [comment]
Hello,

The first version that supports go1.17 is v1.42.0.

Before that, unless you rebuild the binary on your own (and even so I'm not sure of the result), we cannot provide any guarantee on the support of a version of Go that did not exist when the version was created. 

Then either you use go1.1.6 or golangci-lint v1.42.0

**Comment by pauwlsky** [comment]
Thanks for the prompt answer on this @ldez
