### ISSUE TITLE
godot runtime error: slice bounds out of range [:46] with capacity 44

### ISSUE THREAD

**Issue by gonwalk** [golangci/golangci-lint#2402]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

github.com/tetafro/godot version: v1.4.8
github.com/golangci/golangci-lint version: v1.42.0

error message:
```
level=error msg="[runner] Panic: godot: package \"utils\" (isInitialPkg: true, needAnalyzeSource: true): runtime error: slice bounds out of range [:46] with capacity 44: goroutine 5298 [running]:
runtime/debug.Stack(0x13266bb, 0x3c, 0xc0003473c8)
	D:/Go1.16/src/runtime/debug/stack.go:24 +0xa5
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1(0xc001d135c0)
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/golinters/goanalysis/runner_action.go:101 +0x1be panic(0x11f11c0, 0xc0004f3410)
	D:/Go1.16/src/runtime/panic.go:965 +0x1c7
github.com/tetafro/godot.checkCommentForPeriod(0xc001264140, 0x6, 0x3c, 0xc0001609a0, 0xdc, 0xc0 01173200, 0x52, 0xd1, 0x15, 0x1, ...)
	D:/Go1.16/gopath/pkg/mod/github.com/tetafro/godot@v1.4.8/checks.go:81 +0x4a5
github.com/tetafro/godot.checkComments(0xc002823680, 0x3, 0x3, 0xc0007cb050, 0xc, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
	D:/Go1.16/gopath/pkg/mod/github.com/tetafro/godot@v1.4.8/checks.go:40 +0x2da
github.com/tetafro/godot.Run(0xc00121fb00, 0xc0011d8000, 0xc0007cb050, 0xc, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	D:/Go1.16/gopath/pkg/mod/github.com/tetafro/godot@v1.4.8/godot.go:63 +0x2f8
github.com/golangci/golangci-lint/pkg/golinters.NewGodot.func1.1(0xc001ab0dd0, 0x11ee1f889, 0x1bcc280, 0xc001b6ce28, 0x2)
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/golinters/godot.go:50 +0x1ba
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc001d135c0)
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/golinters/goanalysis/runner_action.go:187 +0xa12
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/golinters/goanalysis/runner_action.go:105 +0x31
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0019e1ea0, 0x126d94f, 0x5, 0xc004855f70)
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/timeutils/stopwatch.go:111 +0x54
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc001d135c0)
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/golinters/goanalysis/runner_action.go:104 +0x98
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc000fecae0, 0xc001d135c0)
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0x68
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	D:/Go1.16/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.42.0/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x316
"
level=warning msg="[runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: godot: package \"utils\" (isInitialPkg: true, needAnalyzeSource: true): runtime error: slice bounds out of range [:46] with capacity 44"
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version

golangci-lint has version v1.42.0 built from (unknown, mod sum: "h1:hqf1zo6zY3GKGjjBk3ttdH22tGwF6ZRpk6j6xyJmE8I=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml

 govet:
    # report about shadowed variables
    check-shadowing: true

    # settings per analyzer
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    # enable or disable analyzers by name
    # run `go tool vet help` to see all analyzers
    enable:
      - atomicalign
    enable-all: false
    disable:
      - shadow
    disable-all: false
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```
```
go version go1.16.7 windows/amd64
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Go1.16\gopath\pkg\mod
set GOOS=windows
set GOPATH=D:\Go1.16\gopath
set GOPROXY=https://goproxy.cn
set GOROOT=D:\Go1.16
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go1.16\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.7
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx~1\AppData\Local\Temp\go-build3525136965=/tmp/go-build -gno-record-gcc-switches
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v

level=info msg="[config_reader] Config search paths: [./ C:\\Users\\xxxC:\\Users C:\\]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (name|exports_file|deps|files|imports|types_sizes|compiled_files) took 191.2478ms"
level=error msg="Running error: context loading failed: no go files to analyze"
level=info msg="Memory: 4 samples, avg is 22.4MB, max is 22.5MB"
level=info msg="Execution took 293.8903ms"


```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
package utils


var HttpClient *http.Client

func InitHttp() {
	HttpClient = &http.Client{}
}

type HttpClient struct{}

func NewHttpClient() *HttpClient {
	httpClient := HttpClient{}

	return &httpClient
}
...
```

</details>

**Comment by ldez** [comment]
Hello,

The provided configuration file is invalid.
The code example doesn't compile.
The "Verbose output of running" is not related to the problem.

could you edit the issue and provide the right information? Thank you.
