### ISSUE TITLE
panic when running "revive" with all rules in default config

### ISSUE THREAD

**Issue by leonklingele** [golangci/golangci-lint#2524]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

`golangci-lint` panics when running the "revive" linter with all rules in default config. IMO, sensible defaults should be used which do not cause a panic.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.44.0 built from 617470f on 2022-01-25T11:22:07Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
linters-settings:
  revive:
    enable-all-rules: true
```

</details>

### Go environment

<details>

```console
$ go version && go env
—
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v --disable-all --enable revive ./...
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 1 linters: [revive]
INFO [loader] Go packages loading at mode 7 (compiled_files|files|name) took 226.884078ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 720.057µs
panic: not enough arguments for line-length-limit rule, expected 1, got 0. Please check the rule's documentation

goroutine 518 [running]:
github.com/mgechev/revive/rule.checkNumberOfArguments(...)
	github.com/mgechev/revive@v1.1.3/rule/utils.go:190
github.com/mgechev/revive/rule.(*LineLengthLimitRule).Apply(0xc00032dd50, 0xc000835440, {0x0, 0x0, 0x0})
	github.com/mgechev/revive@v1.1.3/rule/line-length-limit.go:22 +0x18b
github.com/mgechev/revive/lint.(*File).lint(0xc00006b7a8, {0xc0002d4800, 0x44, 0x80}, {0x0, 0x3fe999999999999a, {0x0, 0x0}, 0x1, 0xc000835440, ...}, ...)
	github.com/mgechev/revive@v1.1.3/lint/file.go:105 +0x19b
github.com/mgechev/revive/lint.(*Package).lint.func1(0xc00006b6a0)
	github.com/mgechev/revive@v1.1.3/lint/package.go:173 +0x85
created by github.com/mgechev/revive/lint.(*Package).lint
	github.com/mgechev/revive@v1.1.3/lint/package.go:172 +0xb1
```

</details>

### Code example or link to a public repository

<details>

```sh
# Step to reproduce

cd $(mktemp -d)
git clone https://github.com/leonklingele/dnsbench
cd dnsbench

cat <<EOF > .golangci.yml
linters-settings:
  revive:
    enable-all-rules: true
EOF

golangci-lint run -v --disable-all --enable revive ./...
[…]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 1 linters: [revive]
INFO [loader] Go packages loading at mode 7 (compiled_files|files|name) took 226.884078ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 720.057µs
panic: not enough arguments for line-length-limit rule, expected 1, got 0. Please check the rule's documentation

goroutine 518 [running]:
github.com/mgechev/revive/rule.checkNumberOfArguments(...)
	github.com/mgechev/revive@v1.1.3/rule/utils.go:190
github.com/mgechev/revive/rule.(*LineLengthLimitRule).Apply(0xc00032dd50, 0xc000835440, {0x0, 0x0, 0x0})
	github.com/mgechev/revive@v1.1.3/rule/line-length-limit.go:22 +0x18b
github.com/mgechev/revive/lint.(*File).lint(0xc00006b7a8, {0xc0002d4800, 0x44, 0x80}, {0x0, 0x3fe999999999999a, {0x0, 0x0}, 0x1, 0xc000835440, ...}, ...)
	github.com/mgechev/revive@v1.1.3/lint/file.go:105 +0x19b
github.com/mgechev/revive/lint.(*Package).lint.func1(0xc00006b6a0)
	github.com/mgechev/revive@v1.1.3/lint/package.go:173 +0x85
created by github.com/mgechev/revive/lint.(*Package).lint
	github.com/mgechev/revive@v1.1.3/lint/package.go:172 +0xb1
```

</details>

**Comment by ldez** [comment]
Hello,

It's expected: enable all rules doesn't mean that you don't have to configure the rule.

> not enough arguments for line-length-limit rule, expected 1, got 0. Please check the rule's documentation.
