### ISSUE TITLE
Panic: buildssa: package "randx" (isInitialPkg: true, needAnalyzeSource: true)

### ISSUE THREAD

**Issue by lx-world** [golangci/golangci-lint#2679]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Error running golangci-lint run

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.45.0 built from (unknown, mod sum: "h1:T2oCVkYoeckBxcNS6DTYiSXN2QcTNuAWaHyLGfqzMlU=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```

</details>

### Go environment

<details>

```console
$ go version && go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE=".cache/go-build"
GOENV=".config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK="go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1941441636=/tmp/go-build -gno-record-gcc-switches"
Verbose output of running
详情
Code example or link to a public repository
详情
@[lx-world](https://github.com/lx-world) lx-world added the [bug](https://github.com/golangci/golangci-lint/labels/bug) label [6 days ago](https://github.com/golangci/golangci-lint/issues/2654#event-6263574033)[](https://github.com/marketplace/boring-cyborg-add-labels-to-prs-based-on-filepaths)
@[boring-cyborg](https://github.com/marketplace/boring-cyborg-add-labels-to-prs-based-on-filepaths)
 
boring-cyborg bot commented [6 days ago](https://github.com/golangci/golangci-lint/issues/2654#issuecomment-1071978642)
Hey, thank you for opening your first Issue ! 🙂 If you would like to contribute we have a [guide for contributors](https://golangci-lint.run/contributing/quick-start/)[](https://github.com/lx-world).

@[lx-world](https://github.com/lx-world) lx-world mentioned this issue [6 days ago](https://github.com/golangci/golangci-lint/issues/2654#ref-issue-1170906525)
https://github.com/golangci/golangci-lint/issues/2649[](https://github.com/ldez)
 Open
@[ldez](https://github.com/ldez)
 
Member
ldez commented [6 days ago](https://github.com/golangci/golangci-lint/issues/2654#issuecomment-1072278957)[](https://github.com/ldez)
Hello,

can you provide a reproducible context (full example or public repo)?

@[ldez](https://github.com/ldez) ldez changed the title Error about go1.18 go.work(workspace) Error about go1.18 workspace [6 days ago](https://github.com/golangci/golangci-lint/issues/2654#event-6265373648)[](https://github.com/ldez)
@[ldez](https://github.com/ldez) ldez changed the title Error about go1.18 workspace Error with go1.18 workspace [6 days ago](https://github.com/golangci/golangci-lint/issues/2654#event-6265374415)[](https://github.com/ldez)
@[ldez](https://github.com/ldez) ldez added the [feedback required](https://github.com/golangci/golangci-lint/labels/feedback%20required) label [6 days ago](https://github.com/golangci/golangci-lint/issues/2654#event-6265375019)[](https://github.com/lx-world)
@[lx-world](https://github.com/lx-world)
 
Author
lx-world commented [3 days ago](https://github.com/golangci/golangci-lint/issues/2654#issuecomment-1073289311)[](https://github.com/bombsimon) • 
Project
 A
  -go.mod
  -go.sum
 B
  -go.mod
  -go.sum

go.work

now ， golangcli-lint run

@[bombsimon](https://github.com/bombsimon)
 
Member
bombsimon commented [3 days ago](https://github.com/golangci/golangci-lint/issues/2654#issuecomment-1073305183)[](https://github.com/steakyan) • 
Not reproducible, please provide your real code.

$ tree
.
├── A
│   ├── go.mod
│   └── main.go
└── B
    ├── go.mod
    └── main.go

2 directories, 4 files
$ tail A/main.go B/main.go
==> A/main.go <==
package main

import "fmt"

func main() {

        fmt.Println("vim-go")
}

==> B/main.go <==
package main

import "fmt"

func main() {
        fmt.Println("vim-go")

}
$ golangci-lint run --print-issued-lines=false
B/main.go:7: File is not `gofumpt`-ed (gofumpt)
A/main.go:6: File is not `gofumpt`-ed (gofumpt)
A/main.go:5: unnecessary leading newline (whitespace)
@[steakyan](https://github.com/steakyan)
 
steakyan commented [3 days ago](https://github.com/golangci/golangci-lint/issues/2654#issuecomment-1073529818)[](https://github.com/glebsts) • 
I think this may be the problem of go.work, I could reproduce the problem as follow:

~/go/src/github.com/user/hello$` tree

├── A
│   ├── go.mod
│   └── main.go
├── B
│   ├── go.mod
│   └── main.go
└── go.work
~/go/src/github.com/user/hello$ cat A/go.mod A/main.go
module github.com/user/hello/A

go 1.18
package A

import "fmt"

func main() {

        fmt.Println("vim-go")
}

func A() {
        fmt.Println("A")
}
~/go/src/github.com/user/hello$ cat B/go.mod  B/main.go
module github.com/user/hello/B

go 1.18
package main

import (
        "fmt"
        "github.com/user/hello/A"
)

func main() {

        fmt.Println("vim-go")
        A.A()
}
~/go/src/github.com/user/hello$ cat go.work
go 1.18

use (
    ./A
    ./B
)
I could run this code by

~/go/src/github.com/user/hello$ go run B/main.go
vim-go
A

but when I try to run golangci-lint, I get the results as below

~/go/src/github.com/user/hello$ golangci-lint run
ERRO [linters context] typechecking error: pattern ./...: directory prefix . does not contain modules listed in go.work or their selected dependencies
My go version is go version go1.18 linux/amd64 and golangci-lint version is golangci-lint has version v1.45.0 built from (unknown, mod sum: "h1:T2oCVkYoeckBxcNS6DTYiSXN2QcTNuAWaHyLGfqzMlU=") on (unknown)

@[glebsts](https://github.com/glebsts)
 
glebsts commented [3 days ago](https://github.com/golangci/golangci-lint/issues/2654#issuecomment-1073611883)[](https://github.com/lx-world)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) • 
I get same error when run go test -v ./... after converting to multi-module workspace with same structure. This test run command I used to run before conversion, so it was quite natural.. but it doesn't work anymore. Had to run this command in every module subdirectory instead. Seems like same case.

@lx-world

 
 
Leave a comment
未选择任何文件
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/golangci/golangci-lint/blob/7bbbe77e5e68cdbecad5e25fc44810afd8f3d48c/.github/CONTRIBUTING.md) and [code of conduct](https://github.com/golangci/golangci-lint/blob/7bbbe77e5e68cdbecad5e25fc44810afd8f3d48c/CODE_OF_CONDUCT.md).
Assignees
No one assigned
Labels
[bug](https://github.com/golangci/golangci-lint/labels/bug)
[feedback required](https://github.com/golangci/golangci-lint/labels/feedback%20required)
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

Notifications
Customize
You’re receiving notifications because you authored the thread.
5 participants
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
ERRO [runner] Panic: buildssa: package "randx" (isInitialPkg: true, needAnalyzeSource: true): E: goroutine 20344 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        /home/f/go/pkg/mod/github.com/golangci/golangci-lint@v1.45.0/pkg/golinters/goanalysis/runner_action.go:101 +0x155
panic({0x142bae0, 0xc0076eed50})
        /usr/local/go/src/runtime/panic.go:838 +0x207
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc009842dd0, {0x16e36d0?, 0xc0076eed50?}, 0x0)
        /home/f/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:237 +0x5b1
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc009842dd0, {0x16e36a8?, 0xc005142660?}, 0x0)
        /home/f/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:233 +0x708
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc009842dd0, {0x16e3608?, 0xc010e986c0?}, 0x0)
        /home/f/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:209 +0x448
golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0xc009842dd0, {0x16e3608?, 0xc010e986c0?})
        /home/f/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/methods.go:145 +0x70
golang.org/x/tools/go/ssa.(*Package).build(0xc006e87b00)
        /home/f/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/builder.go:2284 +0x111
sync.(*Once).doSlow(0xc009842dd0?, 0xc009b17a40?)
        /usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
golang.org/x/tools/go/ssa.(*Package).Build(...)
        /home/f/go/pkg/mod/golang.org/x/tools@v0.1.10/go/ssa/builder.go:2272
golang.org/x/tools/go/analysis/passes/buildssa.run(0xc009842c30)
        /home/f/go/pkg/mod/golang.org/x/tools@v0.1.10/go/analysis/passes/buildssa/buildssa.go:72 +0x2ee
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc003d91a10)
        /home/f/go/pkg/mod/github.com/golangci/golangci-lint@v1.45.0/pkg/golinters/goanalysis/runner_action.go:187 +0x9c4
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        /home/f/go/pkg/mod/github.com/golangci/golangci-lint@v1.45.0/pkg/golinters/goanalysis/runner_action.go:105 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc000a54870, {0x149743f, 0x8}, 0xc003c44f48)
        /home/f/go/pkg/mod/github.com/golangci/golangci-lint@v1.45.0/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc00092b3e0?)
        /home/f/go/pkg/mod/github.com/golangci/golangci-lint@v1.45.0/pkg/golinters/goanalysis/runner_action.go:104 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc003d91a10)
        /home/f/go/pkg/mod/github.com/golangci/golangci-lint@v1.45.0/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        /home/f/go/pkg/mod/github.com/golangci/golangci-lint@v1.45.0/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: buildssa: package "randx" (isInitialPkg: true, needAnalyzeSource: true): E
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: buildssa: package "randx" (isInitialPkg: true, needAnalyzeSource: true): E
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,


As I explained [here](https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1070528726) and [here](https://github.com/golangci/golangci-lint/pull/2438), if you are using generics you have to set the following configuration:


```yml
run:
    go: 1.18
```

https://golangci-lint.run/usage/configuration/#run-configuration

**Comment by lx-world** [comment]
> 

ok,  thanks

**Comment by lx-world** [comment]
> Hello,
> 
> As I explained [here](https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1070528726) and [here](https://github.com/golangci/golangci-lint/pull/2438), if you are using generics you have to set the following configuration:
> 
> ```yaml
> run:
>     go: 1.18
> ```
> 
> https://golangci-lint.run/usage/configuration/#run-configuration

ok, thanks
