### ISSUE TITLE
Unparam crash

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#277]
```
[runner] Panic stack trace: goroutine 4349 [running]:\nruntime/debug.Stack(0xd3614e, 0x12, 0xc03a882ea8)\n\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/[secure]/[secure]-lint/pkg/lint.Runner.runLinterSafe.func1(0xc03a883b48, 0xc0363a7260, 0xe, 0xe, 0xe71860, 0xc035dcf0b0)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/lint/runner.go:87 +0xb7\npanic(0xbe0600, 0x14de8f0)\n\t/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/panic.go:513 +0x1b9\ngithub.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil.(*visitor).function(0xc03a883230, 0xc0102ac8c0)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil/visit.go:57 +0xf2\ngithub.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil.(*visitor).function(0xc03a883230, 0xc0102c5b80)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil/visit.go:60 +0x14d\ngithub.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil.(*visitor).program(0xc03a883230)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil/visit.go:40 +0xa1\ngithub.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil.AllFunctions(0xc0152d4e60, 0xc041e943c0)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/ssa/ssautil/visit.go:27 +0x4b\ngithub.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/callgraph/cha.CallGraph(0xc0152d4e60, 0xc015e5e000)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/vendor/github.com/[secure]/tools/go/callgraph/cha/cha.go:41 +0xd6\ngithub.com/[secure]/[secure]-lint/vendor/github.com/[secure]/unparam/check.(*Checker).Check(0xc041d45200, 0xc041d45200, 0xc041d2ca20, 0xc03a883830, 0x40b6c8, 0xc75640)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/vendor/github.com/[secure]/unparam/check/check.go:198 +0x3ce\ngithub.com/[secure]/[secure]-lint/pkg/golinters.Unparam.Run(0xe6c8c0, 0xc0005be3c0, 0xc03fa91260, 0xc03665ab00, 0xcc7b4b, 0x7, 0xc000054500, 0xc0000547a0)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/golinters/unparam.go:31 +0xe0\ngithub.com/[secure]/[secure]-lint/pkg/lint.Runner.runLinterSafe(0xc0363a7260, 0xe, 0xe, 0xe71860, 0xc035dcf0b0, 0xe6c8c0, 0xc0005be3c0, 0xc036640ee0, 0xe6bb00, 0x160b580, ...)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/lint/runner.go:93 +0x1ab\ngithub.com/[secure]/[secure]-lint/pkg/lint.Runner.runWorker.func1()\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/lint/runner.go:127 +0xd6\ngithub.com/[secure]/[secure]-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc036611450, 0xcc7b4b, 0x7, 0xc03a883e40)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/timeutils/stopwatch.go:75 +0x50\ngithub.com/[secure]/[secure]-lint/pkg/lint.Runner.runWorker(0xc0363a7260, 0xe, 0xe, 0xe71860, 0xc035dcf0b0, 0xe6c8c0, 0xc0005be3c0, 0xc036640ee0, 0xc0366595c0, 0xc036659620, ...)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/lint/runner.go:126 +0x20a\ngithub.com/[secure]/[secure]-lint/pkg/lint.(*Runner).runWorkers.func1(0xc01e6aeeb0, 0xc035dcf800, 0xe6c8c0, 0xc0005be3c0, 0xc036640ee0, 0xc0366595c0, 0xc036659620, 0xc035dcf830, 0x2, 0x2, ...)\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/lint/runner.go:181 +0x13b\ncreated by github.com/[secure]/[secure]-lint/pkg/lint.(*Runner).runWorkers\n\t/home/travis/gopath/src/github.com/[secure]/[secure]-lint/pkg/lint/runner.go:178 +0x1b8\n"
        	            	level=warning msg="[runner] Can't run linter unparam: panic occurred: runtime error: invalid memory address or nil pointer dereference"
```

**Comment by jirfag** [comment]
```
Panic stack trace: goroutine 4072 [running]: runtime/debug.Stack(0xd3726e, 0x12, 0xc0232fca40) /usr/local/go/src/runtime/debug/stack.go:24
0xa7 github.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe.func1(0xc0232fdb48, 0xc039d149a0, 0xe, 0xe, 0xe77280, 0xc039e475f0) /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:87
0xb7 panic(0xbe15c0, 0x14918f0) /usr/local/go/src/runtime/panic.go:513
0x1b9 github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc016aa9180) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:57
0xf2 github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc016aa8dc0) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc0153a0780) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc0153a0500) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc0153a0dc0) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc019252140) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc015398b40) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc015398a00) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc000f41400) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc000f412c0) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc0232f2640) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc000f41180) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc000f40f00) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc000f403c0) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc00e2fe280) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).function(0xc0232fd618, 0xc00e2fe140) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:60
0x14d github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.(*visitor).program(0xc0232fd618) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:40
0xa1 github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil.AllFunctions(0xc00fcdf0e0, 0xc0232fd6e0) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/tools/go/ssa/ssautil/visit.go:27
0x4b github.com/golangci/golangci-lint/vendor/github.com/golangci/interfacer/check.(*Checker).Check(0xc02afafbc0, 0xc02afafbc0, 0x10, 0xc0232fd830, 0x40b6b8, 0xc76740) /home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/interfacer/check/check.go:143
0x150 github.com/golangci/golangci-lint/pkg/golinters.Interfacer.Run(0xe722e0, 0xc000147b60, 0xc029a60a80, 0xc039e3dd40, 0xcef5af, 0xa, 0xe77280, 0xc0291be630) /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/golinters/interfacer.go:27
0x81 github.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe(0xc039d149a0, 0xe, 0xe, 0xe77280, 0xc039e475f0, 0xe722e0, 0xc000147b60, 0xc039e17b90, 0xe712a0, 0x15be4e0, ...) /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:93
0x1ab github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker.func1() /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:127
0xd6 github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc03ab41950, 0xcef5af, 0xa, 0xc0232fde40) /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:75
0x50 github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker(0xc039d149a0, 0xe, 0xe, 0xe77280, 0xc039e475f0, 0xe722e0, 0xc000147b60, 0xc039e17b90, 0xc039e45860, 0xc039e458c0, ...) /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:126
0x20a github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers.func1(0xc023b1c5b0, 0xc039e47d40, 0xe722e0, 0xc000147b60, 0xc039e17b90, 0xc039e45860, 0xc039e458c0, 0xc039e45920, 0x4, 0x4, ...) /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:181
0x13b created by github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers /home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:178
0x1b8
```

**Comment by jirfag** [comment]
from #214:
```
goroutine 2271 [running]:\nruntime/debug.Stack(0xcdceba, 0x12, 0xc01298d1f8)\n\t/usr/local/go/src/runtime/debug/stack.go:24
0xa7\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe.func1(0xc01298db48, 0xc016e79b00, 0xc, 0xc, 0xe0a4e0, 0xc019935020)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:76
0xb7\npanic(0xb92c00, 0x13e18b0)\n\t/usr/local/go/src/runtime/panic.go:513
0x1b9\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).function(0xc01298d618, 0xc025d22b40)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:57
0xf2\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).function(0xc01298d618, 0xc025d22a00)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:60
0x14d\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).function(0xc01298d618, 0xc025d13180)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:60
0x14d\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.(*visitor).program(0xc01298d618)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:40
0xa1\ngithub.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil.AllFunctions(0xc0254bc820, 0xc01298d6e0)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/ssa/ssautil/visit.go:27
0x4b\ngithub.com/golangci/golangci-lint/vendor/mvdan.cc/interfacer/check.(*Checker).Check(0xc026807f80, 0xc026807f80, 0xc0285cbed0, 0xc01298d830, 0x40b6b8, 0xc1fae0)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/vendor/mvdan.cc/interfacer/check/check.go:143
0x150\ngithub.com/golangci/golangci-lint/pkg/golinters.Interfacer.Run(0xe05c20, 0xc0001f9f80, 0xc026807e60, 0xc00a1a8880, 0xc95ec2, 0xa, 0xc000041a40, 0xc0000427a0)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/golinters/interfacer.go:27
0x81\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe(0xc016e79b00, 0xc, 0xc, 0xe0a4e0, 0xc019935020, 0xe05c20, 0xc0001f9f80, 0xc006908f00, 0xe04c60, 0x150e038, ...)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:82
0x1ab\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runWorker.func1()\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:116
0xd6\ngithub.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc00e3e06e0, 0xc95ec2, 0xa, 0xc01298de40)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:75
0x50\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runWorker(0xc016e79b00, 0xc, 0xc, 0xe0a4e0, 0xc019935020, 0xe05c20, 0xc0001f9f80, 0xc006908f00, 0xc0069091a0, 0xc006909260, ...)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:115
0x20a\ngithub.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers.func1(0xc0263b51d0, 0xc019935500, 0xe05c20, 0xc0001f9f80, 0xc006908f00, 0xc0069091a0, 0xc006909260, 0xc0069092c0, 0x4, 0x4, ...)\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:170
0x13b\ncreated by github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers\n\t/home/ubuntu/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:167
0x1b8\n
```
