### ISSUE TITLE
ssa: blank label causes a crash

### ISSUE THREAD

**Issue by flimzy** [golangci/golangci-lint#3131]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Since 1.46, `golangci-lint` is crashing on one of our repos.  With today's release of 1.49.0, and it still crashing, I finally decided to create a minimal reproduction case, and found that it's actually quite trivial:  A blank label causes a crash.  Now I don't think a blank label is ever useful... it can't be referenced, AFAIK.  So this is really just a stupid bit of code that I'll clean up in our code base to get things working, but I thought it deserved a report as well.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.49.0 built from cc2d97f3 on 2022-08-24T10:24:37Z
```

</details>

### Configuration file

<details>
Using default config...

```console
$ cat .golangci.yml
$ cat .golangci.*
cat: '.golangci.*': No such file or directory

```

</details>

### Go environment

<details>

```console
$ go version && go env
$ go version && go env
go version go1.18.1 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jonhall/.cache/go-build"
GOENV="/home/jonhall/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jonhall/go/pkg/mod"
GONOPROXY="gitlab.com/FlashbackSRS/priv,github.com/invopop,github.com/hubuc"
GONOSUMDB="gitlab.com/FlashbackSRS/priv,github.com/invopop,github.com/hubuc"
GOOS="linux"
GOPATH="/home/jonhall/go"
GOPRIVATE="gitlab.com/FlashbackSRS/priv,github.com/invopop,github.com/hubuc"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jonhall/src/x/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2090775115=/tmp/go-build -gno-record-gcc-switches"

```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /home/jonhall/src/x /home/jonhall/src /home/jonhall /home /] 
INFO [lintersdb] Active 7 linters: [errcheck gosimple govet ineffassign staticcheck typecheck unused] 
INFO [loader] Go packages loading at mode 575 (imports|name|types_sizes|compiled_files|deps|exports_file|files) took 33.406769ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 71.724µs 
INFO [linters context/goanalysis] analyzers took 5.940978ms with top 10 stages: printf: 769.178µs, ctrlflow: 411.73µs, errorsas: 397.363µs, fact_deprecated: 347.049µs, SA9002: 338.753µs, SA4029: 298.198µs, atomic: 293.72µs, S1004: 240.63µs, S1037: 239.448µs, SA4013: 234.588µs 
ERRO [runner] Panic: S1029: package "main" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildir.IR: goroutine 296 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:101 +0x155
panic({0xf71d20, 0xc000fe4270})
        runtime/panic.go:884 +0x212
honnef.co/go/tools/internal/sharedcheck.CheckRangeStringRunes(0xc000fe9110)
        honnef.co/go/tools@v0.3.3/internal/sharedcheck/lint.go:25 +0x17b
honnef.co/go/tools/simple.CheckRangeStringRunes(0xf531e0?)
        honnef.co/go/tools@v0.3.3/simple/lint.go:1605 +0x19
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc000a482d0)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:187 +0x9d6
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:105 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0001eba90, {0x109240f, 0x5}, 0xc001087f48)
        github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x0?)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:104 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc000a482d0)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: S1029: package "main" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildir.IR 
INFO [runner] processing took 2.904µs with stages: autogenerated_exclude: 601ns, max_same_issues: 521ns, nolint: 300ns, max_from_linter: 291ns, skip_dirs: 260ns, cgo: 120ns, filename_unadjuster: 120ns, path_prettifier: 110ns, skip_files: 110ns, exclude: 100ns, path_shortener: 41ns, exclude-rules: 40ns, max_per_file_from_linter: 40ns, severity-rules: 40ns, source_code: 40ns, identifier_marker: 40ns, sort_results: 40ns, diff: 30ns, uniq_by_line: 30ns, path_prefixer: 30ns 
INFO [runner] linters took 19.09651ms with stages: goanalysis_metalinter: 19.066924ms 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: S1029: package "main" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildir.IR
 
INFO Memory: 2 samples, avg is 35.9MB, max is 38.1MB 
INFO Execution took 57.69614ms                    

```

</details>

### Code example or link to a public repository

<details>

```go
package main

func main() {
_:
}
```

</details>

**Comment by ldez** [comment]
Hello,

Seems to be problem with staticcheck.

```console
$ staticcheck ./...                
panic: no types.Object for ast.Ident _ @ /home/ldez/sources/go/src/github.com/golangci/sandbox/main.go:4:1

goroutine 136 [running]:
honnef.co/go/tools/go/ir.(*Package).objectOf(0xc000302120, 0xc0004876e0)
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:2616 +0x205
honnef.co/go/tools/go/ir.(*Function).labelledBlock(0xc0003268c0, 0xc0004876e0)
        /home/ldez/sources/golangci-lint/go-tools/go/ir/func.go:194 +0x45
honnef.co/go/tools/go/ir.(*builder).stmt(0xc0003efb00?, 0xc0003268c0, {0x9d6a10?, 0xc000487700?})
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:2224 +0xd7
honnef.co/go/tools/go/ir.(*builder).stmtList(0x0?, 0x0?, {0xc000283fa0?, 0x1, 0x0?})
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:855 +0x67
honnef.co/go/tools/go/ir.(*builder).stmt(0xc0003268c0?, 0xc0003268c0, {0x9d6530?, 0xc000299920?})
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:2338 +0xd31
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc0003efb00, 0xc0003268c0)
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:2450 +0x453
honnef.co/go/tools/go/ir.(*builder).buildFuncDecl(0xc000326780?, 0xc000302120, 0xc000299950)
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:2488 +0x195
honnef.co/go/tools/go/ir.(*Package).build(0xc000302120)
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:2594 +0xc52
sync.(*Once).doSlow(0xc0003b21c0?, 0xc0002e80f0?)
        /home/ldez/.gvm/gos/go1.18.5/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /home/ldez/.gvm/gos/go1.18.5/src/sync/once.go:59
honnef.co/go/tools/go/ir.(*Package).Build(...)
        /home/ldez/sources/golangci-lint/go-tools/go/ir/builder.go:2512
honnef.co/go/tools/internal/passes/buildir.run(0xc0003a5e10)
        /home/ldez/sources/golangci-lint/go-tools/internal/passes/buildir/buildir.go:86 +0x368
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc0004f5590, {0x9d7b58?, 0xc00029e320})
        /home/ldez/sources/golangci-lint/go-tools/lintcmd/runner/runner.go:989 +0x614
honnef.co/go/tools/lintcmd/runner.genericHandle({0x9d7b58?, 0xc00029e320}, {0x9d7b58?, 0xc00029e1e0?}, 0xc0001bdfd0?, 0xc0002df9f0, 0xc0004ef330)
        /home/ldez/sources/golangci-lint/go-tools/lintcmd/runner/runner.go:814 +0x102
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers
        /home/ldez/sources/golangci-lint/go-tools/lintcmd/runner/runner.go:1058 +0x705
```

ping @dominikh

**Comment by dominikh** [comment]
TIL. FWIW, the same bug is present in go/ssa, not just my fork.

**Comment by dominikh** [comment]
https://github.com/dominikh/go-tools/commit/0c085726a43c410cac20e948d19b3c63b8c9b379 fixes it in Staticcheck. The fix for go/ssa should look very similar, if not identical.

**Comment by ldez** [comment]
I just add the video about this bug https://www.youtube.com/watch?v=R_odJnFIqPA by @flimzy because it's funny to have a video about that :smiley:

**Comment by ldez** [comment]
The problem seems fixed inside go/ssa too, so I close this issue.
