### ISSUE TITLE
Can't run linter megacheck: panic occured

### ISSUE THREAD

**Issue by quantonganh** [golangci/golangci-lint#32]
golangci-lint run -v:

```
INFO[0000] Active linters: [megacheck govet errcheck structcheck ineffassign varcheck deadcode gas]
INFO[0000] Found paths for analysis for 459.186µs: [. ./cmd ./cmd/load ./lib ./models]
INFO[0008] Program loading took 8.768935722s
INFO[0011] SSA repr building took 3.050474608s
INFO[0012] worker.4 took 4.286801ms with stages: ineffassign: 3.145384ms, errcheck: 346.462µs, deadcode: 260.268µs, structcheck: 230.44µs
INFO[0012] worker.1 took 4.653629ms with stages: gas: 3.904082ms, varcheck: 674.395µs
INFO[0012] worker.2 took 158.615506ms with stages: govet: 158.552628ms
INFO[0017] Panic stack trace: goroutine 2263 [running]:
runtime/debug.Stack(0x17d70b6, 0x11, 0xc444064908)
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/golangci/golangci-lint/pkg.runLinterSafe.func1(0xc444065d10)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/runner.go:34 +0xc2
panic(0x16daac0, 0xc474fca170)
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:502 +0x229
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint(0xc444065688, 0xc42019c180, 0xc420154420, 0xc44f004be0, 0x1743580, 0x1c135e0, 0xc44fda96a8)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:446 +0x2e7c
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lintutil.(*runner).lint(0xc44fda97c0, 0xc42019c180, 0xc420154420, 0xc44f004be0, 0x0, 0x0, 0x0)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lintutil/util.go:292 +0xc8
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lintutil.Lint(0xc45afa2240, 0x3, 0x4, 0xc42019c180, 0xc420154420, 0xc44f004be0, 0xc444065928, 0x4, 0xc44fda9900, 0x1011ff9, ...)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lintutil/util.go:248 +0x1f5
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lintutil.ProcessFlagSet(0xc45af2e6c0, 0x3, 0x4, 0xc45af2e660, 0xc42019c180, 0xc420154420, 0xc44f004be0, 0x4, 0x2, 0xc452b83780)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lintutil/util.go:203 +0x615
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/cmd/megacheck.Run(0xc42019c180, 0xc420154420, 0xc44f004be0, 0x1010101, 0xc44a603360, 0xc44193ef78, 0x1890ec0)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/cmd/megacheck/megacheck.go:124 +0x74a
github.com/golangci/golangci-lint/pkg/golinters.Megacheck.Run(0x10101, 0x188a280, 0xc4201a11a0, 0xc45af23800, 0x102a909, 0x8, 0xc432861bc0, 0x2, 0xc420057480)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/golinters/megacheck.go:42 +0x7d
github.com/golangci/golangci-lint/pkg.runLinterSafe(0x188a280, 0xc4201a11a0, 0xc45af23800, 0x1889500, 0xc42078e445, 0x0, 0x0, 0x0,0x1881020, 0xc474f8d2e0)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/runner.go:38 +0x9f
github.com/golangci/golangci-lint/pkg.runWorker.func1()
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/runner.go:61 +0x64
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc44856bc40, 0x17c4e96, 0x9, 0xc420057660)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:73 +0x53
github.com/golangci/golangci-lint/pkg.runWorker(0x188a280, 0xc4201a11a0, 0xc45af23800, 0xc44854bf80, 0xc45af2e4e0, 0xc438359b28, 0x8)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/runner.go:60 +0x185
github.com/golangci/golangci-lint/pkg.(*SimpleRunner).runWorkers.func1(0xc438359ac0, 0x188a280, 0xc4201a11a0, 0xc45af23800, 0xc44854bf80, 0xc45af2e4e0, 0xc45af2e540, 0x4, 0x4, 0x2)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/runner.go:118 +0x117
created by github.com/golangci/golangci-lint/pkg.(*SimpleRunner).runWorkers
        /Users/quanta/go/src/github.com/golangci/golangci-lint/pkg/runner.go:115 +0x1e6

INFO[0017] worker.3 took 5.245747545s with stages: megacheck: 5.245730941s
INFO[0017] Workers idle times: #1: 5.242094403s, #2: 5.08820943s, #4: 5.242487759s
INFO[0017] Can't run linter megacheck: panic occured: panic: runtime error: invalid memory address or nil pointer dereference, stack: goroutine 2782 [running]:
runtime/debug.Stack(0xc48de310b8, 0x16ee1a0, 0x1c8efa0)
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint.func1.1(0xc47b2c2090, 0x13)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:427 +0x6e
panic(0x16ee1a0, 0x1c8efa0)
        /usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:502 +0x229
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/staticcheck.(*Checker).CheckDeprecated.func1(0x1884fc0, 0xc4202e7800, 0x0)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/staticcheck/lint.go:2376 +0x145
go/ast.inspector.Visit(0xc463f72940, 0x1884fc0, 0xc4202e7800, 0xc4202e77e0, 0x1ca2fe0)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x1882660, 0xc463f72940, 0x1884fc0, 0xc4202e7800)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0x1882660, 0xc463f72940, 0x1884700, 0xc4201c2140)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:136 +0x102b
go/ast.Walk(0x1882660, 0xc463f72940, 0x18849c0, 0xc4200bc660)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:196 +0x1b0c
go/ast.walkStmtList(0x1882660, 0xc463f72940, 0xc4200e6300, 0xb, 0x10)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:32 +0x81
go/ast.Walk(0x1882660, 0xc463f72940, 0x1884680, 0xc4207ac600)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:224 +0x1b61
go/ast.Walk(0x1882660, 0xc463f72940, 0x1884b00, 0xc4207ac630)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:344 +0xd6d
go/ast.walkDeclList(0x1882660, 0xc463f72940, 0xc420c20280, 0x2, 0x2)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:38 +0x81
go/ast.Walk(0x1882660, 0xc463f72940, 0x1884a80, 0xc42011a280)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:353 +0x2650
go/ast.Inspect(0x1884a80, 0xc42011a280, 0xc463f72940)
        /usr/local/Cellar/go/1.10.1/libexec/src/go/ast/walk.go:385 +0x4b
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/staticcheck.(*Checker).CheckDeprecated(0xc4485768a0, 0xc43e30a440)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/staticcheck/lint.go:2406 +0xa5
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/staticcheck.(*Checker).CheckDeprecated-fm(0xc43e30a440)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/staticcheck/lint.go:235 +0x34
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint.func1(0xc47b2c2090, 0xc48ddea6e0, 0xc47b2c2060, 0x13, 0xc43e30a440)
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:436 +0xc7
created by github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint
        /Users/quanta/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:424 +0x25a0

INFO[0017] processing took 3.645µs with stages: max_same_issues: 2.115µs, path_prettifier: 448ns, max_from_linter: 258ns, uniq_by_line: 218ns, diff: 200ns, exclude: 135ns, cgo: 121ns, nolint: 81ns, max_per_file_from_linter: 69ns
Congrats! No issues were found.
INFO[0017] Extracting issued lines took 0s
INFO[0017] Memory: 101 samples, avg is 1158.7MB, max is 1850.9MB
INFO[0017] Execution took 17.185922259s
```

**Comment by golangci** [comment]
@quantonganh thank you for the issue!
it's the same bug as #33 . Check please in master:
`go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`
