### ISSUE TITLE
goanalysis_metalinter panics on code with generics and 'performance' tag enabled

### ISSUE THREAD

**Issue by fabiomargarido** [golangci/golangci-lint#3249]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

After adding the following code with generics to the project:
```go
func MapSlice[T any, M any](source []T, predicate func(T) M) []M {
	mapped := make([]M, len(source))

	for i, item := range source {
		mapped[i] = predicate(item)
	}

	return mapped
}
```

golangci-lint panics on goanalysis_metalinter whenever the `performance` tag is enabled for gocritic. Disabling the tag makes the issue go away.
```
golangci-lint run ./...
ERRO [runner] Panic: gocritic: package "foundation" (isInitialPkg: true, needAnalyzeSource: true): /opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181: assertion failed: goroutine 8861 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:101 +0x104
panic({0x1056758e0, 0x1400996dde0})
	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/panic.go:884 +0x204
go/types.assert(0xa8?)
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/types/errors.go:27 +0x60
go/types.(*StdSizes).Sizeof(0x140001af150, {0x1058403a8?, 0x140058a0510})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181 +0x324
github.com/go-critic/go-critic/checkers.(*rangeValCopyChecker).VisitStmt(0x14014e9f8e0, {0x105843838?, 0x1400463c460?})
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/rangeValCopy_checker.go:68 +0xac
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile.func1({0x10583fe30?, 0x1400463c460?})
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/internal/astwalk/stmt_walker.go:23 +0x60
go/ast.inspector.Visit(0x1400996ddb0, {0x10583fe30?, 0x1400463c460?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:386 +0x38
go/ast.Walk({0x10583d0a0?, 0x1400996ddb0?}, {0x10583fe30?, 0x1400463c460?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:51 +0x4c
go/ast.walkStmtList({0x10583d0a0, 0x1400996ddb0}, {0x14004ef3400?, 0x3, 0x14005881a40?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:32 +0x8c
go/ast.Walk({0x10583d0a0?, 0x1400996ddb0?}, {0x10583f7c8?, 0x14005881b30?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:234 +0x53c
go/ast.Inspect(...)
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:397
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile(0x14013f09630?, 0x14005888180?)
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/internal/astwalk/stmt_walker.go:21 +0x140
github.com/go-critic/go-critic/framework/linter.(*Checker).Check(...)
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/framework/linter/linter.go:129
github.com/golangci/golangci-lint/pkg/golinters.runGocriticOnFile(0x1400746e900, 0x14000440d7c?, {0x1400f3ad000, 0x68, 0x1400375c1b0?})
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:138 +0xa0
github.com/golangci/golangci-lint/pkg/golinters.runGocriticOnPackage(0x1400746e900, {0x1400f3ad000, 0x68, 0x80}, {0x14006e03340, 0x2, 0x20?})
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:126 +0x15c
github.com/golangci/golangci-lint/pkg/golinters.goCriticWrapper.run({0x14000534388?, 0x14000534000?, {0x105843bf8?, 0x140001af150?}}, 0x14005c38820)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:86 +0x1d8
github.com/golangci/golangci-lint/pkg/golinters.NewGocritic.func1(0x1056de2e0?)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:41 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0x14002a38bc0)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:187 +0x958
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:105 +0x20
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0x14001633180, {0x10535ff06, 0x8}, 0x14003c83730)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x104ed73a0?)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:104 +0x74
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x14002a38bc0)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb0
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x168
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: gocritic: package "foundation" (isInitialPkg: true, needAnalyzeSource: true): /opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181: assertion failed
WARN [linters context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goanalysis_metalinter: gocritic: package "foundation" (isInitialPkg: true, needAnalyzeSource: true): /opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181: assertion failed

make: *** [lint-check] Error 3
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.48.0 built from (unknown, mod sum: "h1:hRiBNk9iRqdAKMa06ntfEiLyza1/3IE9rHLNJaek4a8=") on (unknown)
Smart, fast linters runner. Run it in cloud for every GitHub pull request on https://golangci.com

Usage:
  golangci-lint [flags]
  golangci-lint [command]

Available Commands:
  cache       Cache control and information
  completion  Generate the autocompletion script for the specified shell
  config      Config
  help        Help
  linters     List current linters configuration
  run         Run the linters
  version     Version

Flags:
      --color string              Use color when printing; can be 'always', 'auto', or 'never' (default "auto")
  -j, --concurrency int           Concurrency (default NumCPU) (default 8)
      --cpu-profile-path string   Path to CPU profile output file
  -h, --help                      help for golangci-lint
      --mem-profile-path string   Path to memory profile output file
      --trace-path string         Path to trace output file
  -v, --verbose                   verbose output
      --version                   Print version

Use "golangci-lint [command] --help" for more information about a command.
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl

run:
  issues-exit-code: 1

```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.19.1 darwin/arm64
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/fabio.margarido/Library/Caches/go-build"
GOENV="/Users/fabio.margarido/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/fabio.margarido/go/pkg/mod"
GONOPROXY="code.<REDACTED>/*,go.<REDACTED>/*"
GONOSUMDB="code.<REDACTED>/*,go.<REDACTED>/*"
GOOS="darwin"
GOPATH="/Users/fabio.margarido/go"
GOPRIVATE="code.<REDACTED>/*,go.<REDACTED>/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/fabio.margarido/Projects/<REDACTED>/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k0/4yywlmbs6h38d0yjvsly0stcczh6fl/T/go-build3357686742=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/fabio.margarido/Projects/<REDACTED> /Users/fabio.margarido/Projects/<REDACTED> /Users/fabio.margarido/Projects/<REDACTED> /Users/fabio.margarido/Projects/<REDACTED> /Users/fabio.margarido/Projects /Users/fabio.margarido /Users /]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 35 linters: [bodyclose deadcode depguard dogsled dupl errcheck exhaustive exportloopref goconst gocritic gocyclo gofmt goimports gomnd gosec gosimple govet ineffassign misspell nakedret nolintlint prealloc predeclared revive staticcheck structcheck stylecheck thelper tparallel typecheck unconvert unparam varcheck whitespace wsl]
INFO [loader] Go packages loading at mode 575 (exports_file|imports|types_sizes|compiled_files|deps|files|name) took 399.508583ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 1.443209ms
INFO [linters context/goanalysis] analyzers took 30.43515832s with top 10 stages: buildir: 12.129629697s, gocritic: 9.547065792s, exhaustive: 1.410731382s, fact_deprecated: 1.021412504s, printf: 973.149971ms, inspect: 811.94358ms, ctrlflow: 784.08237ms, buildssa: 772.63446ms, fact_purity: 439.892549ms, nilness: 402.643707ms
ERRO [runner] Panic: gocritic: package "foundation" (isInitialPkg: true, needAnalyzeSource: true): /opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181: assertion failed: goroutine 11592 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:101 +0x104
panic({0x1017458e0, 0x14032593c30})
	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/panic.go:884 +0x204
go/types.assert(0xa8?)
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/types/errors.go:27 +0x60
go/types.(*StdSizes).Sizeof(0x140000451c0, {0x1019103a8?, 0x140151597d0})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181 +0x324
github.com/go-critic/go-critic/checkers.(*rangeValCopyChecker).VisitStmt(0x1402eddf420, {0x101913838?, 0x14007d48b40?})
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/rangeValCopy_checker.go:68 +0xac
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile.func1({0x10190fe30?, 0x14007d48b40?})
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/internal/astwalk/stmt_walker.go:23 +0x60
go/ast.inspector.Visit(0x14032714300, {0x10190fe30?, 0x14007d48b40?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:386 +0x38
go/ast.Walk({0x10190d0a0?, 0x14032714300?}, {0x10190fe30?, 0x14007d48b40?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:51 +0x4c
go/ast.walkStmtList({0x10190d0a0, 0x14032714300}, {0x1400df04680?, 0x3, 0x1400ec33728?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:32 +0x8c
go/ast.Walk({0x10190d0a0?, 0x14032714300?}, {0x10190f7c8?, 0x14015158c90?})
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:234 +0x53c
go/ast.Inspect(...)
	/opt/homebrew/Cellar/go/1.19/libexec/src/go/ast/walk.go:397
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile(0x1402edcdb00?, 0x1400a77e180?)
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/internal/astwalk/stmt_walker.go:21 +0x140
github.com/go-critic/go-critic/framework/linter.(*Checker).Check(...)
	/Users/fabio.margarido/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/framework/linter/linter.go:129
github.com/golangci/golangci-lint/pkg/golinters.runGocriticOnFile(0x140080a5920, 0x14000cf755c?, {0x1402f0b0000, 0x68, 0x1400ef8ac60?})
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:138 +0xa0
github.com/golangci/golangci-lint/pkg/golinters.runGocriticOnPackage(0x140080a5920, {0x1402f0b0000, 0x68, 0x80}, {0x1400d583f50, 0x2, 0x14010789110?})
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:126 +0x15c
github.com/golangci/golangci-lint/pkg/golinters.goCriticWrapper.run({0x1400024a388?, 0x1400024a000?, {0x101913bf8?, 0x140000451c0?}}, 0x140034a9040)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:86 +0x1d8
github.com/golangci/golangci-lint/pkg/golinters.NewGocritic.func1(0x1017ae2e0?)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/gocritic.go:41 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0x1400237cab0)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:187 +0x958
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:105 +0x20
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0x140005091d0, {0x10142ff06, 0x8}, 0x140018acf30)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x100fa73a0?)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_action.go:104 +0x74
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x1400237cab0)
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb0
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/Users/fabio.margarido/go/pkg/mod/github.com/golangci/golangci-lint@v1.48.0/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x168
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: gocritic: package "foundation" (isInitialPkg: true, needAnalyzeSource: true): /opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181: assertion failed
WARN [linters context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
INFO [runner] processing took 6.916µs with stages: max_same_issues: 2.792µs, nolint: 792ns, identifier_marker: 583ns, skip_dirs: 583ns, max_from_linter: 500ns, cgo: 292ns, autogenerated_exclude: 291ns, source_code: 167ns, path_prettifier: 125ns, skip_files: 84ns, exclude: 84ns, exclude-rules: 83ns, path_shortener: 83ns, max_per_file_from_linter: 83ns, sort_results: 83ns, severity-rules: 83ns, uniq_by_line: 83ns, path_prefixer: 42ns, diff: 42ns, filename_unadjuster: 41ns
INFO [runner] linters took 5.690688667s with stages: goanalysis_metalinter: 5.690497s, structcheck: 29.958µs
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goanalysis_metalinter: gocritic: package "foundation" (isInitialPkg: true, needAnalyzeSource: true): /opt/homebrew/Cellar/go/1.19/libexec/src/go/types/sizes.go:181: assertion failed

INFO Memory: 63 samples, avg is 816.9MB, max is 1291.2MB
INFO Execution took 6.101273333s
```

</details>

### Code example or link to a public repository

<details>

```go
package foundation

func MapSlice[T any, M any](source []T, predicate func(T) M) []M {
	mapped := make([]M, len(source))

	for i, item := range source {
		mapped[i] = predicate(item)
	}

	return mapped
}
```

</details>

**Comment by ldez** [comment]
Hello,

can you try to use the latest stable version: v1.49.0
