### ISSUE TITLE
Panic: unparam: package "test" (isInitialPkg: true, needAnalyzeSource: true): ...go1.19.4/src/go/types/sizes.go:181:

### ISSUE THREAD

**Issue by pmalek** [golangci/golangci-lint#3456]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

When running on a repo I get this error:

```
ERRO [runner] Panic: unparam: package "test" (isInitialPkg: true, needAnalyzeSource: true): /Users/USER/.gvm/gos/go1.19.4/src/go/types/sizes.go:181: assertion failed: goroutine 24550 [running]:
runtime/debug.Stack()
        /Users/USER/.gvm/gos/go1.19.4/src/runtime/debug/stack.go:24 +0x64
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:102 +0x104
panic({0x105d54b40, 0x1400e7bce70})
        /Users/USER/.gvm/gos/go1.19.4/src/runtime/panic.go:884 +0x204
go/types.assert(0x28?)
        /Users/USER/.gvm/gos/go1.19.4/src/go/types/errors.go:27 +0x60
go/types.(*StdSizes).Sizeof(0x14000135120, {0x105f27128?, 0x1400aebcba0})
        /Users/USER/.gvm/gos/go1.19.4/src/go/types/sizes.go:181 +0x324
mvdan.cc/unparam/check.(*Checker).checkFunc(0x1400ec112c0, 0x14015b9c900, 0x140007a08a0?)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/mvdan.cc/unparam@v0.0.0-20220706161116-678bad134442/check/check.go:598 +0x77c
mvdan.cc/unparam/check.(*Checker).Check(0x1400ec112c0)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/mvdan.cc/unparam@v0.0.0-20220706161116-678bad134442/check/check.go:378 +0x5e4
github.com/golangci/golangci-lint/pkg/golinters.runUnparam(0x1400ec302d0, 0x140010b9ab0)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/unparam.go:75 +0x1d8
github.com/golangci/golangci-lint/pkg/golinters.NewUnparam.func1(0x105dbee40?)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/unparam.go:28 +0x30
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0x14002818890)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:188 +0x958
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:106 +0x20
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0x140014df0e0, {0x105a28173, 0x7}, 0x1400329e730)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x105485b40?)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:105 +0x74
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x14002818890)
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb0
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        /Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x168
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: unparam: package "test" (isInitialPkg: true, needAnalyzeSource: true): /Users/USER/.gvm/gos/go1.19.4/src/go/types/sizes.go:181: assertion failed
WARN [linters_context] wastedassign is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
```

The stack trace leads to this line in go source: https://github.com/golang/go/blob/go1.19.4/src/go/types/sizes.go#L181

---

Tried running `uparam` on the same repo but no crash was observed:

```
go install mvdan.cc/unparam@latest
unparam -tests -exported ./...
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.50.1 built from (unknown, mod sum: "h1:C829clMcZXEORakZlwpk7M4iDw2XiwxxKaG504SZ9zY=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
run:
  timeout: 5m
  skip-dirs:
  - pkg/clientset
  - config/
  - third_party/
  build-tags:
  - integration_tests
  - e2e_tests
linters:
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - errorlint
  - exhaustive
  - exportloopref
  - gci
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kong/gateway-operator)
  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/api/apps/v1
        alias: appsv1
      - pkg: k8s.io/api/admission/v1
        alias: admissionv1
      - pkg: k8s.io/api/certificates/v1
        alias: certificatesv1

      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: sigs.k8s.io/gateway-api/apis/(v[\w\d]+)
        alias: gateway${1}

      - pkg: github.com/kong/gateway-operator/internal/types
        alias: gwtypes
  revive:
    rules:
      - name: context-as-argument
        # TODO: re-add this rule after https://github.com/golangci/golangci-lint/issues/3280
        # is resolved and released.
        # arguments:
        #   - "allowTypesBefore": "*testing.T"
        disabled: true
  exhaustive:
    default-signifies-exhaustive: true
issues:
  max-same-issues: 0
  fix: true
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.19.4 darwin/arm64
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/USER/Library/Caches/go-build"
GOENV="/Users/USER/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/USER/.gvm/pkgsets/go1.19.4/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/USER/.gvm/pkgsets/go1.19.4/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/USER/.gvm/gos/go1.19.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/USER/.gvm/gos/go1.19.4/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/USER/code_/gateway-operator/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0m/_63w01516tgf3cftmp9h7ylm0000gn/T/go-build379502785=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

Link to GH action that failed: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3833664906/jobs/6525341176#step:6:374

**Comment by ldez** [comment]
Hello,

can you try with the same version of `unparam` (`v0.0.0-20220706161116-678bad134442`) as golangci-lint?

**Comment by pmalek** [comment]
It seems that bumping `unparam` to currently latest version `v0.0.0-20221223090309-7455f1af531d` does fix the issue. Thanks for the suggestion @ldez!
