### ISSUE TITLE
Panic from goimports

### ISSUE THREAD

**Issue by y0ssar1an** [golangci/golangci-lint#348]
```
Panic stack trace: goroutine 12045 [running]:
runtime/debug.Stack(0xdbe662, 0x12, 0xc08b579180)
	tools/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe.func1(0xc08b579b48, 0xc089d66620, 0xe, 0xe, 0xef3500, 0xc08b040960)
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:87 +0xb7
panic(0xc5d540, 0x14f0950)
	tools/usr/local/go/src/runtime/panic.go:513 +0x1b9
golang.org/x/tools/imports.(*pass).importIdentifier(...)
	tools/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/fix.go:307
golang.org/x/tools/imports.(*pass).load(0xc09472f600, 0xc09472f600)
	tools/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/fix.go:339 +0x525
golang.org/x/tools/imports.fixImportsDefault(0xc09496eac0, 0xc09472f400, 0xc000d25e60, 0x57, 0x1e7, 0x3e7)
	tools/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/fix.go:504 +0x2f9
golang.org/x/tools/imports.Process(0xc000d25e60, 0x57, 0xc0949c4800, 0x1e7, 0x3e7, 0x146cd80, 0x0, 0x1b8, 0x369, 0x0, ...)
	tools/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/imports.go:66 +0x72b
github.com/golangci/gofmt/goimports.Run(0xc000d25e60, 0x57, 0x0, 0x0, 0x0, 0x0, 0x0)
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/gofmt/goimports/golangci.go:17 +0xab
github.com/golangci/golangci-lint/pkg/golinters.Gofmt.Run(0xc08b02fb01, 0xeedde0, 0xc0001570e0, 0xc08a3d3880, 0xc08af5c9c0, 0xd62a5d, 0x9, 0xef3500, 0xc08a4c6270)
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/golinters/gofmt.go:115 +0x11d
github.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe(0xc089d66620, 0xe, 0xe, 0xef3500, 0xc08b040960, 0xeedde0, 0xc0001570e0, 0xc08ae369a0, 0xeec9e0, 0xc00030019a, ...)
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:93 +0x19d
github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker.func1()
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:127 +0xd6
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc08a4a45a0, 0xd62a5d, 0x9, 0xc06629be40)
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:75 +0x50
github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker(0xc089d66620, 0xe, 0xe, 0xef3500, 0xc08b040960, 0xeedde0, 0xc0001570e0, 0xc08ae369a0, 0xc069b8d380, 0xc069b8d3e0, ...)
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:126 +0x20a
github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers.func1(0xc0872b5410, 0xc08b0410b0, 0xeedde0, 0xc0001570e0, 0xc08ae369a0, 0xc069b8d380, 0xc069b8d3e0, 0xc0887cefc0, 0x8, 0x8, ...)
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:181 +0x13b
created by github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers
	tools/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:178 +0x1b8
level=warning msg="[runner] Can't run linter goimports: panic occurred: runtime error: invalid memory address or nil pointer dereference"
```
I got this nil pointer dereference while running the latest `golangci-lint` built by Go 1.11.4. It appears to originate from [this line in `goimports`](https://github.com/golangci/golangci-lint/blob/609de3254c4b022fb07e5d5626f65180e696c60c/vendor/golang.org/x/tools/imports/fix.go#L307).

I'm vendoring `golangci-lint` with Go modules. Here's some lines from `go.sum` that might be relevant.
```
golang.org/x/tools v0.0.0-20180221164845-07fd8470d635/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
golang.org/x/tools v0.0.0-20180826000951-f6ba57429505/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
golang.org/x/tools v0.0.0-20181117154741-2ddaf7f79a09/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
golang.org/x/tools v0.0.0-20181220024903-92cdcd90bf52 h1:oOIe9Zzq27JsS/3ACpGF1HwWnWNflZWT/3EvM7mtcEk=
golang.org/x/tools v0.0.0-20181220024903-92cdcd90bf52/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
```

### Environment Details

1. `golangci-lint` version is v1.12.5 (built from source)
2. `cat .golangci.yml`
```yaml
run:
  deadline: 2m
  modules-download-mode: vendor
  tests: true

issues:
  exclude:
    - declaration of "err" shadows declaration
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv).  # the default exclude pattern for errcheck
  exclude-use-default: false
  max-per-linter: 0
  max-same: 0

linters:
  enable-all: true
  disable:
    - gas
    - gocritic
    - gochecknoglobals
    - gochecknoinits
    - dupl
    - lll
    - scopelint
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 18
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
```
3.
```sh
> go version
go version go1.11.4 linux/amd64
```
```sh
> go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cruise/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build534203445=/tmp/go-build -gno-record-gcc-switches"
```
4.
```sh
> golangci-lint run -v
level=info msg="[config_reader] Config search paths: [./ /go/src/github.robot.car/cruise/gulp /go/src/github.robot.car/cruise /go/src/github.robot.car /go/src /go /]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="Gocritic enabled checks: [appendAssign assignOp caseOrder dupArg dupBranchBody dupCase flagDeref ifElseChain regexpMust singleCaseSwitch sloppyLen switchTrue typeSwitchVar underef unlambda unslice defaultCaseOrder]"
level=info msg="[lintersdb] Active 20 linters: [deadcode depguard errcheck goconst gocyclo gofmt goimports golint govet ineffassign interfacer maligned megacheck misspell nakedret prealloc structcheck typecheck unconvert varcheck]"
level=info msg="[loader] Go packages loading at mode load deps types and syntax took 3.982795455s"
level=info msg="[loader] SSA repr building timing: packages building 83.852341ms, total 1.412726656s"
level=info msg="[loader] SSA for megacheck repr building timing: packages building 33.396554ms, total 1.426380404s"
level=info msg="[runner] worker.2 took 428.779067ms with stages: misspell: 184.3265ms, varcheck: 90.258918ms, structcheck: 59.255421ms, errcheck: 53.920205ms, maligned: 22.054204ms, goconst: 18.894953ms"
level=info msg="[runner] worker.1 took 439.75045ms with stages: ineffassign: 289.103823ms, deadcode: 65.811747ms, prealloc: 26.709953ms, unconvert: 22.908215ms, gocyclo: 18.56676ms, nakedret: 16.595147ms, typecheck: 3.281µs"
level=info msg="[runner] worker.8 took 483.705339ms with stages: govet: 483.682861ms"
level=info msg="[runner] worker.3 took 1.1793506s with stages: gofmt: 1.179337491s"
level=info msg="[runner] worker.5 took 2.29637107s with stages: interfacer: 2.296350135s, depguard: 3.678µs"
level=info msg="[runner] worker.6 took 4.662532884s with stages: golint: 4.662508289s"
level=info msg="[runner] worker.4 took 5.844547818s with stages: megacheck: 5.84453361s"
level=warning msg="[runner] Panic stack trace: goroutine 13586 [running]:\nruntime/debug.Stack(0xdbe662, 0x12, 0xc08acaf180)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe.func1(0xc08acafb48, 0xc08a712380, 0xe, 0xe, 0xef3500, 0xc08393f2c0)\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:87 +0xb7\npanic(0xc5d540, 0x14f0950)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngolang.org/x/tools/imports.(*pass).importIdentifier(...)\n\t/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/fix.go:307\ngolang.org/x/tools/imports.(*pass).load(0xc093914200, 0xc093914200)\n\t/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/fix.go:339 +0x525\ngolang.org/x/tools/imports.fixImportsDefault(0xc093754b40, 0xc093914000, 0xc000d1dec0, 0x57, 0x1e7, 0x3e7)\n\t/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/fix.go:504 +0x2f9\ngolang.org/x/tools/imports.Process(0xc000d1dec0, 0x57, 0xc0935adc00, 0x1e7, 0x3e7, 0x146cd80, 0x0, 0x1b8, 0x369, 0x0, ...)\n\t/go/src/github.robot.car/cruise/gulp/vendor/golang.org/x/tools/imports/imports.go:66 +0x72b\ngithub.com/golangci/gofmt/goimports.Run(0xc000d1dec0, 0x57, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/gofmt/goimports/golangci.go:17 +0xab\ngithub.com/golangci/golangci-lint/pkg/golinters.Gofmt.Run(0xc08a777901, 0xeedde0, 0xc00008c600, 0xc083943b20, 0xc08a77ce00, 0xd62a5d, 0x9, 0xef3500, 0xc08393fb30)\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/golinters/gofmt.go:115 +0x11d\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runLinterSafe(0xc08a712380, 0xe, 0xe, 0xef3500, 0xc08393f2c0, 0xeedde0, 0xc00008c600, 0xc08a772540, 0xeec9e0, 0xc0003a223a, ...)\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:93 +0x19d\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runWorker.func1()\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:127 +0xd6\ngithub.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc08a740c80, 0xd62a5d, 0x9, 0xc08a7c5e40)\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:75 +0x50\ngithub.com/golangci/golangci-lint/pkg/lint.Runner.runWorker(0xc08a712380, 0xe, 0xe, 0xef3500, 0xc08393f2c0, 0xeedde0, 0xc00008c600, 0xc08a772540, 0xc08a76f9e0, 0xc08a76fa40, ...)\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:126 +0x20a\ngithub.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers.func1(0xc08a3c1540, 0xc08393fa10, 0xeedde0, 0xc00008c600, 0xc08a772540, 0xc08a76f9e0, 0xc08a76fa40, 0xc08a68cfc0, 0x8, 0x8, ...)\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:181 +0x13b\ncreated by github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers\n\t/go/src/github.robot.car/cruise/gulp/vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go:178 +0x1b8\n"
level=info msg="[runner] worker.7 took 6.949827357s with stages: goimports: 6.949809575s"
level=info msg="[runner] Workers idle times: #1: 6.509725249s, #2: 6.52095236s, #3: 5.770377832s, #4: 1.105300273s, #5: 4.65341891s, #6: 2.28730781s, #8: 6.465747169s"
level=warning msg="[runner] Can't run linter goimports: panic occurred: runtime error: invalid memory address or nil pointer dereference"
level=info msg="[runner] Issues before processing: 247, after processing: 0"
level=info msg="[runner] processing took 95.748783ms with stages: nolint: 80.736175ms, skip_dirs: 4.851046ms, path_prettifier: 4.613478ms, autogenerated_exclude: 3.334279ms, cgo: 1.610625ms, exclude: 590.027µs, uniq_by_line: 2.389µs, source_code: 2.364µs, diff: 1.963µs, max_same_issues: 1.65µs, max_per_file_from_linter: 1.317µs, path_shortener: 1.234µs, max_from_linter: 1.175µs, skip_files: 1.061µs"
level=info msg="Memory: 114 samples, avg is 2238.7MB, max is 4505.8MB"
level=info msg="Execution took 13.808397213s"
```

**Comment by jirfag** [comment]
hi, thank you for reporting!

Does it reproduce with the latest (`go get -u golang.org/x/tools/cmd/goimports`) goimports (without golangci-lint)? Does it reproduce on any open-source project?

**Comment by y0ssar1an** [comment]
Unfortunately, this occurred on a closed-source codebase. I'll update `golangci-lint` to the latest `master` commit and test it again when I get back to work next week.

**Comment by jirfag** [comment]
thank you, and check it with the latest goimports without golangci-lint, please.

**Comment by y0ssar1an** [comment]
I'm pleased to say the panic has gone away in `v1.13.1`! 🎉
