### ISSUE TITLE
govet nilness check is still having issues with generics

### ISSUE THREAD

**Issue by ryancurrah** [golangci/golangci-lint#3559]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

As of golangci-lint 1.51.0 govet `nilness` check has been enabled again for Go version greater than or equal to 1.18.

We have updated to this version found that it still panics on generic code.

 

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.51.0 built from 6d3f06c5 on 2023-02-02T08:24:52Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# options for analysis running
run:
  modules-download-mode: readonly
  deadline: 10m
  timeout: 10m
  issues-exit-code: 0
  tests: true
  skip-files:
    - "mock_.*\\.go"
    - "generated.*\\.go"
    - ".*\\.gen\\.go"
    - ".*_gen\\.go"
    - ".*\\.pb\\.go"

# output configuration options
output:
  format: tab
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false

# all available settings of specific linters
linters-settings:
  govet:
    check-shadowing: false
    disabled:
      - nilness

linters:
  enable:
  - govet
  disable-all: true
```

</details>

### Go environment

<details>

```console
$ go version && go env

```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
[2023-02-03T19:06:55.503Z] level=error msg="[runner] Panic: nilness: package \"genericpkg\" (isInitialPkg: false, needAnalyzeSource: true): internal error: unhandled type *o.CompositeValue: goroutine 30392 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:102 +0x155
panic({0xf41800, 0xc03f954a50})
	runtime/panic.go:884 +0x213
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x13278a8, 0xc03f86c460})
	honnef.co/go/tools@v0.4.0-0.dev.0.20221209223220-58c4d7e4b720/analysis/facts/nilness/nilness.go:234 +0x834
honnef.co/go/tools/analysis/facts/nilness.impl(0xc03f3e3a40, 0xc033ac88c0, 0xc003d49cb8)
	honnef.co/go/tools@v0.4.0-0.dev.0.20221209223220-58c4d7e4b720/analysis/facts/nilness/nilness.go:241 +0x372
honnef.co/go/tools/analysis/facts/nilness.run(0xc03f3e3a40)
	honnef.co/go/tools@v0.4.0-0.dev.0.20221209223220-58c4d7e4b720/analysis/facts/nilness/nilness.go:66 +0x11a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc00504f120)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:188 +0x9df
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:106 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc00238e5f0, {0x10d2c58, 0x7}, 0xc003d49f48)
	github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc01ce43fe0?)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:105 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc00504f120)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb
"
[2023-02-03T19:06:55.503Z] level=warning msg="[runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: nilness: package \"genericpkg\" (isInitialPkg: false, needAnalyzeSource: true): internal error: unhandled type *o.CompositeValue"
```

</details>

### Code example or link to a public repository

<details>

```go
// na
```

</details>

**Comment by ldez** [comment]
can you provide a reproducible example?

**Comment by ryancurrah** [comment]
Yeah give me some time I will post more details

**Comment by ryancurrah** [comment]
Actually it was `staticcheck` `SA4023` that caused it and i cant reproduce with some example code. So I will close this for now and amend my comment in the other discussion.
