### ISSUE TITLE
golangci/golangci-lint:v1.13: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mbana** [golangci/golangci-lint#366]
Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
```sh
golangci-lint has version 1.13 built from 2192097 on 2019-01-21T07:58:29Z
```
2. Config file: `cat .golangci.yml`
```sh
$ cat .golangci.yml
cat: .golangci.yml: No such file or directory
```
3. Go environment: `go version && go env`
```sh
go version go1.11.4 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build228904288=/tmp/go-build -gno-record-gcc-switches"
```
4. Verbose output of running: `golangci-lint run -v`
```sh
$ golangci-lint run --print-issued-lines=false --fast -v
level=info msg="[config_reader] Config search paths: [./ /root/go_samples/run_golangci_lint_in_docker /root/go_samples /root /]"
level=info msg="[lintersdb] Active 7 linters: [deadcode errcheck govet ineffassign structcheck typecheck varcheck]"
panic: runtime error: index out of range

goroutine 34 [running]:
github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/internal/packagesdriver.GetSizesGolist(0xef1040, 0xc00027d380, 0x0, 0x0, 0x0, 0xc00053bea0, 0xa, 0xa, 0xc000034034, 0x2c, ...)
	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go:89 +0x470
github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages.getSizes(0xc0001e7f48, 0x0, 0x0, 0x0, 0x0)
	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages/golist.go:394 +0x9a
github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages.goListDriver.func1(0xc0001e7f48, 0xc000186f40, 0xc000186f50, 0xc000456240)
	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages/golist.go:47 +0x2f
created by github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages.goListDriver
	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages/golist.go:46 +0x1744
```

---
I've got some Golang examples in: https://github.com/banaio/go_samples.

```sh
$ cd /tmp && \
    git clone git@github.com:banaio/go_samples.git && \
    go_samples/run_golangci_lint_in_docker && \ 
    make up
docker-compose up --force-recreate --always-recreate-deps --renew-anon-volumes --remove-orphans
Recreating run_golangci_lint_in_docker ... done
Attaching to run_golangci_lint_in_docker
run_golangci_lint_in_docker    | go version go1.11.4 linux/amd64
run_golangci_lint_in_docker    | GOARCH="amd64"
run_golangci_lint_in_docker    | GOBIN=""
run_golangci_lint_in_docker    | GOCACHE="/root/.cache/go-build"
run_golangci_lint_in_docker    | GOEXE=""
run_golangci_lint_in_docker    | GOFLAGS=""
run_golangci_lint_in_docker    | GOHOSTARCH="amd64"
run_golangci_lint_in_docker    | GOHOSTOS="linux"
run_golangci_lint_in_docker    | GOOS="linux"
run_golangci_lint_in_docker    | GOPATH="/go"
run_golangci_lint_in_docker    | GOPROXY=""
run_golangci_lint_in_docker    | GORACE=""
run_golangci_lint_in_docker    | GOROOT="/usr/local/go"
run_golangci_lint_in_docker    | GOTMPDIR=""
run_golangci_lint_in_docker    | GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
run_golangci_lint_in_docker    | GCCGO="gccgo"
run_golangci_lint_in_docker    | CC="gcc"
run_golangci_lint_in_docker    | CXX="g++"
run_golangci_lint_in_docker    | CGO_ENABLED="1"
run_golangci_lint_in_docker    | GOMOD=""
run_golangci_lint_in_docker    | CGO_CFLAGS="-g -O2"
run_golangci_lint_in_docker    | CGO_CPPFLAGS=""
run_golangci_lint_in_docker    | CGO_CXXFLAGS="-g -O2"
run_golangci_lint_in_docker    | CGO_FFLAGS="-g -O2"
run_golangci_lint_in_docker    | CGO_LDFLAGS="-g -O2"
run_golangci_lint_in_docker    | PKG_CONFIG="pkg-config"
run_golangci_lint_in_docker    | GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build124727749=/tmp/go-build -gno-record-gcc-switches"
run_golangci_lint_in_docker    |   ---> installing github.com/golangci/golangci-lint/cmd/golangci-lint ... 
run_golangci_lint_in_docker    | golangci/golangci-lint info checking GitHub for tag 'v1.13'
run_golangci_lint_in_docker    | golangci/golangci-lint info found version: 1.13 for v1.13/linux/amd64
run_golangci_lint_in_docker    | golangci/golangci-lint info installed /go/bin/golangci-lint
run_golangci_lint_in_docker    | golangci-lint has version 1.13 built from 2192097 on 2019-01-21T07:58:29Z
run_golangci_lint_in_docker    |   ---> running golangci-lint ... 
run_golangci_lint_in_docker    | total 44K
run_golangci_lint_in_docker    | drwxr-xr-x 8 root root  256 Jan 21 10:23 .
run_golangci_lint_in_docker    | drwxr-xr-x 3 root root 4.0K Jan 21 10:42 ..
run_golangci_lint_in_docker    | -rw-r--r-- 1 root root  216 Jan 21 10:39 Makefile
run_golangci_lint_in_docker    | -rw-r--r-- 1 root root 1.4K Jan 21 10:34 docker-compose.yml
run_golangci_lint_in_docker    | -rw-r--r-- 1 root root 2.6K Jan 21 10:11 go.mod
run_golangci_lint_in_docker    | -rw-r--r-- 1 root root  23K Jan 21 10:11 go.sum
run_golangci_lint_in_docker    | -rw-r--r-- 1 root root   93 Jan 21 10:02 main.go
run_golangci_lint_in_docker    | drwxr-xr-x 3 root root   96 Jan 21 10:23 pkg
run_golangci_lint_in_docker    | level=info msg="[config_reader] Config search paths: [./ /root/go_samples/run_golangci_lint_in_docker /root/go_samples /root /]"
run_golangci_lint_in_docker    | level=info msg="[lintersdb] Active 7 linters: [deadcode errcheck govet ineffassign structcheck typecheck varcheck]"
run_golangci_lint_in_docker    | panic: runtime error: index out of range
run_golangci_lint_in_docker    | 
run_golangci_lint_in_docker    | goroutine 24 [running]:
run_golangci_lint_in_docker    | github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/internal/packagesdriver.GetSizesGolist(0xef1040, 0xc00018d1a0, 0x0, 0x0, 0x0, 0xc0005cf720, 0xa, 0xa, 0xc000034034, 0x2c, ...)
run_golangci_lint_in_docker    | 	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go:89 +0x470
run_golangci_lint_in_docker    | github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages.getSizes(0xc0005cf688, 0x0, 0x0, 0x0, 0x0)
run_golangci_lint_in_docker    | 	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages/golist.go:394 +0x9a
run_golangci_lint_in_docker    | github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages.goListDriver.func1(0xc0005cf688, 0xc00009f650, 0xc00009f660, 0xc000714100)
run_golangci_lint_in_docker    | 	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages/golist.go:47 +0x2f
run_golangci_lint_in_docker    | created by github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages.goListDriver
run_golangci_lint_in_docker    | 	/Users/denis/go/src/github.com/golangci/golangci-lint/vendor/golang.org/x/tools/go/packages/golist.go:46 +0x1744
run_golangci_lint_in_docker exited with code 2
```

**Comment by jirfag** [comment]
Hi, thank you! I will take a look

**Comment by jirfag** [comment]
thank you for perfect reproduction example!
I could reproduce it:
```bash
$ GL_DEBUG=linters_output GOPACKAGESPRINTGOLISTERRORS=1 golangci-lint run --print-issued-lines=false --fast -v
GOROOT=/usr/local/go GOPATH=/go GO111MODULE= PWD=/root/go_samples/run_golangci_lint_in_docker go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe] stderr: <<go: github.com
/StackExchange/wmi@v0.0.0-20181212234831-e0a55b97c705: git init --bare in /go/pkg/mod/cache/vcs/1e27c85e821f18cfbbce893a068065af7efff4ab86f7daf2a8de26813b7ffe62: exit status 128:
        error: could not lock config file /go/pkg/mod/cache/vcs/1e27c85e821f18cfbbce893a068065af7efff4ab86f7daf2a8de26813b7ffe62/config: File exists
        fatal: could not set 'core.repositoryformatversion' to '0'
go: finding github.com/golangci/golangci-lint v1.12.5
go: finding github.com/golangci/gocyclo v0.0.0-20180528144436-0a533e8fa43d
go: finding github.com/golangci/tools v0.0.0-20190108095906-d95fd85c147a
go: finding github.com/coreos/etcd v3.3.11+incompatible
go: finding github.com/gogo/protobuf v1.2.0
go: finding github.com/spf13/afero v1.2.0
go: finding github.com/go-toolsmith/astcopy v1.0.0
go: finding github.com/go-toolsmith/astp v1.0.0
go: finding golang.org/x/sys v0.0.0-20190121090251-770c60269bf0
go: finding golang.org/x/tools v0.0.0-20190118193359-16909d206f00
go: finding github.com/onsi/gomega v1.4.3
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding github.com/mattn/go-isatty v0.0.4
go: finding github.com/golangci/lint-1 v0.0.0-20181222135242-d2cdd8c08219
go: finding github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2
go: finding sourcegraph.com/sourcegraph/go-diff v0.5.0
go: finding github.com/golangci/gofmt v0.0.0-20181222123516-0b8337e80d98
go: finding github.com/golangci/errcheck v0.0.0-20181223084120-ef45e06d44b6
go: finding github.com/nbutton23/zxcvbn-go v0.0.0-20180912185939-ae427f1e4c1d
go: finding github.com/shirou/gopsutil v2.18.12+incompatible
go: finding github.com/go-lintpack/lintpack v0.5.2
go: finding github.com/fatih/color v1.7.0
go: finding github.com/shurcooL/go v0.0.0-20181215222900-0143a8f55f04
go: finding golang.org/x/crypto v0.0.0-20190103213133-ff983b9c42bc
go: finding golang.org/x/net v0.0.0-20190119204137-ed066c81e75e
go: finding github.com/spf13/cobra v0.0.3
>>
panic: runtime error: index out of range
```

1. I will try to fix `go/packages` to report errors properly and don't crash.
2. The problem here that `go/packages` can't fetch the module dependencies.

**Comment by jirfag** [comment]
will be fixed in https://github.com/golangci/golangci-lint/issues/401

**Comment by jirfag** [comment]
go/packages was updated many times after that
