### ISSUE TITLE
golangci-lint panics on Go v1.20 netip package when run on my project

### ISSUE THREAD

**Issue by nomad-software** [golangci/golangci-lint#3916]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I get a panic when running `golangci-lint run` on my project. (linked below)

Similar past issue: https://github.com/golangci/golangci-lint/issues/3533

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.50.1 built from (unknown, mod sum: "h1:C829clMcZXEORakZlwpk7M4iDw2XiwxxKaG504SZ9zY=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
not used.
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.20.5 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/tmp/go-cache"
GOENV="/home/gary/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/tmp/go-mod-cache"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/media/Data/Projects/Go/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR="/tmp"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/media/Data/Projects/Go/stream/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4099994058=/tmp/go-build -gno-record-gcc-switches"

```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /media/Data/Projects/Go/stream /media/Data/Projects/Go /media/Data/Projects /media/Data /media / /home/gary] 
INFO [lintersdb] Active 7 linters: [errcheck gosimple govet ineffassign staticcheck typecheck unused] 
INFO [loader] Go packages loading at mode 575 (exports_file|name|compiled_files|deps|types_sizes|files|imports) took 162.547642ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 1.639627ms 
INFO [linters_context/goanalysis] analyzers took 3.384741731s with top 10 stages: buildir: 2.551067632s, inspect: 261.161465ms, fact_deprecated: 161.837795ms, ctrlflow: 100.746538ms, printf: 97.121625ms, SA5012: 52.315902ms, fact_purity: 46.551022ms, nilness: 36.609371ms, typedness: 28.272855ms, S1038: 10.604593ms 
ERRO [runner] Panic: buildir: package "netip" (isInitialPkg: false, needAnalyzeSource: true): in net/netip.AddrFromSlice: cannot convert Load <[]byte> t0 ([]byte) to [4]byte: goroutine 1576 [running]:
runtime/debug.Stack()
	/opt/go/src/runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/tmp/go-mod-cache/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:102 +0x155
panic({0x14fe300, 0xc0092f67a0})
	/opt/go/src/runtime/panic.go:884 +0x213
honnef.co/go/tools/go/ir.emitConv(0xc00885c640, {0x19396c8, 0xc009478180}, {0x192cbb0?, 0xc00370ecc0}, {0x192c2a0, 0xc003822340})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/emit.go:293 +0xd29
honnef.co/go/tools/go/ir.(*builder).expr0(0xc002159a28, 0xc00885c640, {0x192ff70?, 0xc003822340?}, {0x7, {0x192cbb0, 0xc00370ecc0}, {0x0, 0x0}})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:610 +0x5d7
honnef.co/go/tools/go/ir.(*builder).expr(0x192cd40?, 0xc00885c640, {0x192ff70, 0xc003822340})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:566 +0x1fa
honnef.co/go/tools/go/ir.(*builder).emitCallArgs(0x192cd40?, 0xc00885c640, 0xc003f79200, 0xc003822380, {0x0?, 0x0, 0x8b80c7?})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:975 +0x135
honnef.co/go/tools/go/ir.(*builder).setCall(0x1567e20?, 0xc00885c640, 0xc003822380, 0xc0092ac5e8)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:1037 +0x8e
honnef.co/go/tools/go/ir.(*builder).expr0(0xc002159a28, 0xc00885c640, {0x192ff70?, 0xc003822380?}, {0x7, {0x192cca0, 0xc00358c3f0}, {0x0, 0x0}})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:623 +0x218e
honnef.co/go/tools/go/ir.(*builder).expr(0xc002158e78?, 0xc00885c640, {0x192ff70, 0xc003822380})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:566 +0x1fa
honnef.co/go/tools/go/ir.(*builder).stmt(0xc00885c640?, 0xc00885c640, {0x19304b0?, 0xc001bd75c0?})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:2291 +0x194c
honnef.co/go/tools/go/ir.(*builder).stmtList(...)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:855
honnef.co/go/tools/go/ir.(*builder).switchStmt(0xc002159308?, 0xc00885c640, 0xc0018e5b90, 0x0)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:1366 +0x19a5
honnef.co/go/tools/go/ir.(*builder).stmt(0x20?, 0xc00885c640, {0x1930600?, 0xc0018e5b90?})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:2365 +0x121c
honnef.co/go/tools/go/ir.(*builder).stmtList(0x8bea45?, 0xc0021594f8?, {0xc001bd77e0?, 0x2, 0x8c0650?})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:855 +0x45
honnef.co/go/tools/go/ir.(*builder).stmt(0xc00885c640?, 0xc00885c640, {0x192ff10?, 0xc0018e5bc0?})
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:2338 +0x9b9
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc002159a28, 0xc00885c640)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:2450 +0x3d7
honnef.co/go/tools/go/ir.(*builder).buildFuncDecl(0x0?, 0xc00545db90, 0xc0018e5c20)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:2488 +0x19b
honnef.co/go/tools/go/ir.(*Package).build(0xc00545db90)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:2594 +0xc16
sync.(*Once).doSlow(0xc0035fa620?, 0xc003481d10?)
	/opt/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/opt/go/src/sync/once.go:65
honnef.co/go/tools/go/ir.(*Package).Build(...)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/go/ir/builder.go:2512
honnef.co/go/tools/internal/passes/buildir.run(0xc004941a00)
	/tmp/go-mod-cache/honnef.co/go/tools@v0.3.3/internal/passes/buildir/buildir.go:86 +0x368
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc001130a40)
	/tmp/go-mod-cache/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:188 +0x9d6
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/tmp/go-mod-cache/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:106 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0010e2d70, {0x16c9b40, 0x7}, 0xc0014bbf48)
	/tmp/go-mod-cache/github.com/golangci/golangci-lint@v1.50.1/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc000ed4e40?)
	/tmp/go-mod-cache/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_action.go:105 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc001130a40)
	/tmp/go-mod-cache/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/tmp/go-mod-cache/github.com/golangci/golangci-lint@v1.50.1/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: buildir: package "netip" (isInitialPkg: false, needAnalyzeSource: true): in net/netip.AddrFromSlice: cannot convert Load <[]byte> t0 ([]byte) to [4]byte 
INFO [runner] processing took 2.31µs with stages: max_same_issues: 398ns, nolint: 237ns, skip_dirs: 224ns, max_from_linter: 161ns, skip_files: 105ns, filename_unadjuster: 102ns, exclude: 98ns, path_prettifier: 97ns, cgo: 97ns, sort_results: 92ns, autogenerated_exclude: 92ns, uniq_by_line: 92ns, identifier_marker: 91ns, exclude-rules: 90ns, severity-rules: 87ns, source_code: 87ns, path_shortener: 41ns, diff: 41ns, max_per_file_from_linter: 39ns, path_prefixer: 39ns 
INFO [runner] linters took 1.395398078s with stages: goanalysis_metalinter: 1.39537254s 
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goanalysis_metalinter: buildir: package "netip" (isInitialPkg: false, needAnalyzeSource: true): in net/netip.AddrFromSlice: cannot convert Load <[]byte> t0 ([]byte) to [4]byte
 
INFO Memory: 17 samples, avg is 176.8MB, max is 289.2MB 
INFO Execution took 1.564422038s
```

</details>

### Code example or link to a public repository

<details>
https://github.com/nomad-software/stream
</details>

**Comment by ldez** [comment]
Hello,

You are using v1.50.1 but this version doesn't support go1.20. You have to use at least [v1.51](https://github.com/golangci/golangci-lint/blob/v1.53.3/CHANGELOG.md#v1510).

I recommend using the latest stable version: v1.53.3
