### ISSUE TITLE
megacheck panic

### ISSUE THREAD

**Issue by chappjc** [golangci/golangci-lint#411]
Version: d3bc69dc5b0d60101d1844ef8eb916367169bc7f
No .golangci.yml.
Env:

```
go version go1.12 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jon/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jon/go"
GOPROXY=""
GORACE=""
GOROOT="/home/jon/go112"
GOTMPDIR=""
GOTOOLDIR="/home/jon/go112/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build923520179=/tmp/go-build -gno-record-gcc-switches"
```

Output:

```
INFO [config_reader] Config search paths: [./ /home/jon/github/decred/dcrdata /home/jon/github/decred /home/jon/github /home/jon /home /] 
INFO [lintersdb] Active 9 linters: [goimports gosimple govet ineffassign misspell staticcheck structcheck unconvert unparam] 
INFO [lintersdb] Optimized sublinters [staticcheck gosimple] into metalinter megacheck 
INFO [loader] Go packages loading at mode load deps types and syntax took 1.332049429s 
INFO [loader] SSA repr building timing: packages building 30.253671ms, total 255.367727ms 
INFO [loader] Packages that do not compile: [github.com/decred/dcrdata/v4/cmd/rebuilddb github.com/decred/dcrdata/v4/cmd/rebuilddb2 github.com/decred/dcrdata/v4/cmd/scanblocks] 
INFO [runner] worker.29 took 16.049µs             
INFO [runner] worker.24 took 30.093µs             
INFO [runner] worker.19 took 1.04µs               
INFO [runner] worker.20 took 356ns                
INFO [runner] worker.28 took 678ns                
INFO [runner] worker.21 took 329ns                
INFO [runner] worker.23 took 796ns                
INFO [runner] worker.2 took 294ns                 
INFO [runner] worker.25 took 17.74µs              
INFO [runner] worker.3 took 6.727µs               
INFO [runner] worker.5 took 466ns                 
INFO [runner] worker.4 took 1.13µs                
INFO [runner] worker.15 took 1.479µs              
INFO [runner] worker.26 took 413ns                
INFO [runner] worker.32 took 283ns                
INFO [runner] worker.14 took 642ns                
INFO [runner] worker.30 took 303ns                
INFO [runner] worker.16 took 369ns                
INFO [runner] worker.12 took 9.02µs               
INFO [runner] worker.17 took 1.805µs              
INFO [runner] worker.10 took 656ns                
INFO [runner] worker.8 took 402ns                 
INFO [runner] worker.7 took 41.655µs              
INFO [runner] worker.6 took 18.022µs              
INFO [runner] worker.22 took 1.925212ms with stages: unconvert: 1.89284ms 
INFO [runner] worker.11 took 12.583324ms with stages: structcheck: 12.560719ms 
INFO [runner] worker.27 took 86.029964ms with stages: govet: 86.011625ms 
INFO [runner] worker.13 took 99.324061ms with stages: ineffassign: 99.291216ms 
INFO [runner] worker.31 took 103.704355ms with stages: misspell: 103.678774ms 
INFO [runner] worker.18 took 134.046553ms with stages: unparam: 134.0151ms 
INFO [runner] worker.9 took 713.173484ms with stages: goimports: 713.146057ms 
WARN [runner] Panic stack trace: goroutine 5141 [running]:
runtime/debug.Stack(0xd37120, 0xc038b7cd30, 0xc032f628f8)
	/home/jon/go112/src/runtime/debug/stack.go:24 +0x9d
github.com/golangci/golangci-lint/pkg/lint.(*Runner).runLinterSafe.func1(0xc032f63ce8, 0xc032f63ee0)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:99 +0xfd
panic(0xd0d4a0, 0xc02fc20dc0)
	/home/jon/go112/src/runtime/panic.go:522 +0x1b5
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint(0xc032f63658, 0xc026c5e300, 0x20, 0x20, 0xc032f63620, 0x0, 0x0, 0xc02cf56120)
	/home/jon/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:477 +0x3445
github.com/golangci/golangci-lint/pkg/golinters.runMegacheckCheckers(0xc02cf56140, 0x2, 0x2, 0xc0000b1870, 0xc026c5e300, 0x20, 0x20, 0x2, 0x7, 0xfeb980, ...)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/golinters/megacheck.go:349 +0x1f3
github.com/golangci/golangci-lint/pkg/golinters.megacheck.runMegacheck(0xc000010100, 0xc026c5e300, 0x20, 0x20, 0x0, 0xc0000b19f8, 0x40d709, 0xc02cf24d50, 0x30, 0x30)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/golinters/megacheck.go:303 +0x182
github.com/golangci/golangci-lint/pkg/golinters.megacheck.Run(0x10100, 0xff7060, 0xc00018f4a0, 0xc02cf3e850, 0xc02cef9df0, 0x1, 0x1, 0xffde60, 0xc02cf09100)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/golinters/megacheck.go:243 +0xe8
github.com/golangci/golangci-lint/pkg/lint.(*Runner).runLinterSafe(0xc0000b1ee0, 0xff7060, 0xc00018f4a0, 0xc02ceecb60, 0xc00019d280, 0x0, 0x0, 0x0, 0xfe05a0, 0xc038b7cd30)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:105 +0x16a
github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker.func1()
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:139 +0x64
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc02cf1c7d0, 0xe3a9b7, 0x9, 0xc001442e40)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:75 +0x50
github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker(0xc02cef6240, 0x11, 0x11, 0x1000f20, 0xc02cc5b2c0, 0xff7060, 0xc00018f4a0, 0xc02ceecb60, 0xc02cf0efc0, 0xc02cf0f020, ...)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:138 +0x23b
github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers.func1(0xc02cf33940, 0xc02cf24c90, 0xff7060, 0xc00018f4a0, 0xc02ceecb60, 0xc02cf0efc0, 0xc02cf0f020, 0xc01f957800, 0x20, 0x20, ...)
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:193 +0x163
created by github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers
	/home/jon/go/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:190 +0x1ab
 
INFO [runner] worker.1 took 1.334890725s with stages: megacheck: 1.334884797s 
INFO [runner] Workers idle times: #2: 1.334271438s, #3: 1.334248961s, #4: 1.334231134s, #5: 1.334246264s, #6: 1.333661083s, #7: 1.333825384s, #8: 1.333939398s, #9: 621.533746ms, #10: 1.333956195s, #11: 1.321932552s, #12: 1.334099605s, #13: 1.235296632s, #14: 1.334167838s, #15: 1.334202786s, #16: 1.334140322s, #17: 1.334078635s, #18: 1.200797626s, #19: 1.334314355s, #20: 1.334301865s, #21: 1.334289283s, #22: 1.332509538s, #23: 1.334273925s, #24: 1.334319582s, #25: 1.334261932s, #26: 1.334188934s, #27: 1.248742245s, #28: 1.33429588s, #29: 1.33432846s, #30: 1.334152317s, #31: 1.230914748s, #32: 1.334180339s 
WARN [runner] Can't run linter megacheck: panic occurred: panic: runtime error: invalid memory address or nil pointer dereference: goroutine 6329 [running]:
runtime/debug.Stack(0xc02f7d9360, 0xd1d5e0, 0x16fca30)
	/home/jon/go112/src/runtime/debug/stack.go:24 +0x9d
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint.func1.1(0xc03b9fa310)
	/home/jon/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:458 +0x60
panic(0xd1d5e0, 0x16fca30)
	/home/jon/go112/src/runtime/panic.go:522 +0x1b5
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/simple.(*Checker).LintMakeLenCap.func1(0xfeab80, 0xc023c908c0, 0xfeb401)
	/home/jon/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/simple/lint.go:1365 +0x57b
go/ast.inspector.Visit(0xc021093220, 0xfeab80, 0xc023c908c0, 0xfe2000, 0xc021093220)
	/home/jon/go112/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0xfe2000, 0xc021093220, 0xfeab80, 0xc023c908c0)
	/home/jon/go112/src/go/ast/walk.go:52 +0x66
go/ast.walkExprList(0xfe2000, 0xc021093220, 0xc023b94bd0, 0x1, 0x1)
	/home/jon/go112/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0xfe2000, 0xc021093220, 0xfea980, 0xc023c90900)
	/home/jon/go112/src/go/ast/walk.go:207 +0x2103
go/ast.walkStmtList(0xfe2000, 0xc021093220, 0xc021be4600, 0x19, 0x20)
	/home/jon/go112/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0xfe2000, 0xc021093220, 0xfeab00, 0xc022fc5170)
	/home/jon/go112/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0xfe2000, 0xc021093220, 0xfeaf80, 0xc022fc51a0)
	/home/jon/go112/src/go/ast/walk.go:344 +0xd73
go/ast.walkDeclList(0xfe2000, 0xc021093220, 0xc023c7c200, 0x5, 0x8)
	/home/jon/go112/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0xfe2000, 0xc021093220, 0xfeaf00, 0xc023c7c280)
	/home/jon/go112/src/go/ast/walk.go:353 +0x2659
go/ast.Inspect(...)
	/home/jon/go112/src/go/ast/walk.go:385
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/simple.(*Checker).LintMakeLenCap(0xc02cf10950, 0xc03b9fa310)
	/home/jon/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/simple/lint.go:1382 +0xa0
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint.func1(0xc049560aa0, 0xc02af06f60, 0xc03b9fa310)
	/home/jon/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:469 +0x102
created by github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*Linter).Lint
	/home/jon/go/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:455 +0x1d71
 
INFO [runner] Issues before processing: 1, after processing: 0 
INFO [runner] processing took 401.983µs with stages: nolint: 224.163µs, exclude: 59.264µs, identifier_marker: 54.233µs, autogenerated_exclude: 35.469µs, path_prettifier: 13.124µs, cgo: 6.449µs, skip_dirs: 5.908µs, max_same_issues: 816ns, source_code: 568ns, skip_files: 345ns, diff: 324ns, replacement_builder: 308ns, path_shortener: 300ns, max_from_linter: 229ns, uniq_by_line: 199ns, exclude-rules: 173ns, max_per_file_from_linter: 111ns 
INFO Memory: 30 samples, avg is 741.7MB, max is 1491.6MB 
INFO Execution took 2.954191299s  
```

**Comment by chappjc** [comment]
Aaaah, it seems I build this with a corrupt module cache, probably related to go symlink bug prior to go 1.11.4.  I ran a `go clean -modcache`, rebuilt golangci-lint, and it's working.

**Comment by jirfag** [comment]
Ok, thank you :) Can we close the issue?

**Comment by chappjc** [comment]
'course, sorry.
