### ISSUE TITLE
panic from gocritic and staticcheck

### ISSUE THREAD

**Issue by 3timeslazy** [golangci/golangci-lint#429]
golangci-lint panics on [MontFerret/ferret](https://github.com/MontFerret/ferret)
1. `golangci-lint has version 1.15.0 built from 901cf25 on 2019-02-18T08:22:26Z`
2. `cat: .golangci.yml: No such file or directory`
3. `go version go1.12 darwin/amd64`
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vladimirfetisov/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vladimirfetisov/gocode"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nd/crmgx6395v1gxprwvwg5x9gw0000gn/T/go-build292474987=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
4.`golangci-lint run -v --enable-all`
```
INFO [config_reader] Config search paths: [./ /Users/vladimirfetisov/gocode/src/github.com/MontFerret/ferret /Users/vladimirfetisov/gocode/src/github.com/MontF
erret /Users/vladimirfetisov/gocode/src/github.com /Users/vladimirfetisov/gocode/src /Users/vladimirfetisov/gocode /Users/vladimirfetisov /Users /] 
INFO [lintersdb] Active 31 linters: [deadcode depguard dupl errcheck gochecknoglobals gochecknoinits goconst gocritic gocyclo gofmt goimports golint gosec gosi
mple govet ineffassign interfacer lll maligned misspell nakedret prealloc scopelint staticcheck structcheck stylecheck typecheck unconvert unparam unused varch
eck] 
INFO [lintersdb] Optimized sublinters [staticcheck gosimple unused stylecheck] into metalinter megacheck 
INFO [loader] Go packages loading at mode load deps types and syntax took 3.681961351s 
INFO [loader] SSA repr building timing: packages building 32.339081ms, total 473.371912ms 
INFO [loader] Packages that do not compile: [github.com/MontFerret/ferret/examples] 
pkg/runtime/values/helpers.go:315:2: unreachable code (govet)
        switch input.Type() {
        ^
pkg/stdlib/datetime/helpers_test.go:49:19: `mustLayoutDt` - `layout` always receives `"2006-01-02"` (unparam)
func mustLayoutDt(layout, value string) values.DateTime {
                  ^
pkg/stdlib/math/variance.go:11:70: variance - result 1 (error) is always nil (unparam)
func variance(input *values.Array, sample values.Int) (values.Float, error) {
                                                                     ^
panic: runtime error: index out of range

goroutine 12550 [running]:
github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers.init.16.func1.1.1(0xc011a2a2c0, 0xc0232e5b00)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers/dupArg_checker.go:26 +0x8a
github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers.(*dupArgChecker).VisitExpr(0xc0232d71c0, 0x1b31600, 0xc011a2a2c0)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers/dupArg_checker.go:111 +0x9e
github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk.(*exprWalker).WalkFile.func1(0x1b2cd80, 0xc011a2a2c0, 0x1b2d601)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk/expr_walker.go:23 +0x82
go/ast.inspector.Visit(0xc02fbf8c70, 0x1b2cd80, 0xc011a2a2c0, 0x1b2a8c0, 0xc02fbf8c70)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2cd80, 0xc011a2a2c0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:52 +0x66
go/ast.walkExprList(0x1b2a8c0, 0xc02fbf8c70, 0xc0119df5e0, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2cb80, 0xc011a2a300)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:207 +0x2100
go/ast.walkStmtList(0x1b2a8c0, 0xc02fbf8c70, 0xc011a21900, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2cd00, 0xc0119fb920)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2d1c0, 0xc0119df630)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:98 +0x2c10
go/ast.walkExprList(0x1b2a8c0, 0xc02fbf8c70, 0xc011a21920, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2cd80, 0xc011a2a380)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:137 +0x1074
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2d040, 0xc0119df650)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:196 +0x1b12
go/ast.walkStmtList(0x1b2a8c0, 0xc02fbf8c70, 0xc0119df660, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2cd00, 0xc0119fb950)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2d1c0, 0xc0119df670)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:98 +0x2c10
go/ast.walkExprList(0x1b2a8c0, 0xc02fbf8c70, 0xc011a2a3c0, 0x3, 0x4)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2cd80, 0xc011a2a400)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:137 +0x1074
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2d040, 0xc0119df690)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:196 +0x1b12
go/ast.walkStmtList(0x1b2a8c0, 0xc02fbf8c70, 0xc011a2b680, 0x3, 0x4)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2cd00, 0xc011a40060)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x1b2a8c0, 0xc02fbf8c70, 0x1b2d180, 0xc011a40090)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:344 +0xd6d
go/ast.Inspect(0x1b2d180, 0xc011a40090, 0xc02fbf8c70)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/go/ast/walk.go:385 +0x4b
github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk.(*exprWalker).WalkFile(0xc0232e0ee0, 0xc0117c9400)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk/expr_walker.go:21 +0x135
github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack.(*Checker).Check(0xc0232a7740, 0xc0117c9400, 0xc03010a070, 0xc0011ebe01, 0xc0011ebf98)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/lintpack.go:126 +0x46
github.com/golangci/golangci-lint/pkg/golinters.Gocritic.runOnFile.func1(0xc03010a070, 0xc0117c9400, 0xc0233054f0, 0xc0232e6360, 0xc0232a7740)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/gocritic.go:157 +0x8a
created by github.com/golangci/golangci-lint/pkg/golinters.Gocritic.runOnFile
        /home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/gocritic.go:154 +0xa8
```

**Comment by jirfag** [comment]
Hi! I've fixed it in https://github.com/golangci/golangci-lint/pull/507, please, check.

**Comment by 3timeslazy** [comment]
Hi! It's still falling.
```
WARN [runner/govet] govet error: assign: analysis skipped due to errors in package 
WARN [runner/govet] govet error: atomicalign: analysis skipped due to errors in package 
WARN [runner/govet] govet error: bools: analysis skipped due to errors in package 
WARN [runner/govet] govet error: buildtag: analysis skipped due to errors in package 
WARN [runner/govet] govet error: httpresponse: analysis skipped due to errors in package 
WARN [runner/govet] govet error: loopclosure: analysis skipped due to errors in package 
WARN [runner/govet] govet error: ctrlflow: analysis skipped due to errors in package 
WARN [runner/govet] govet error: lostcancel: failed prerequisites: ctrlflow@github.com/MontFerret/ferret/examples 
WARN [runner/govet] govet error: nilfunc: analysis skipped due to errors in package 
WARN [runner/govet] govet error: printf: analysis skipped due to errors in package 
WARN [runner/govet] govet error: shift: analysis skipped due to errors in package 
WARN [runner/govet] govet error: stdmethods: analysis skipped due to errors in package 
WARN [runner/govet] govet error: tests: analysis skipped due to errors in package 
WARN [runner/govet] govet error: unmarshal: analysis skipped due to errors in package 
WARN [runner/govet] govet error: unsafeptr: analysis skipped due to errors in package 
WARN [runner/govet] govet error: unusedresult: analysis skipped due to errors in package 
WARN [runner/govet] govet error: buildssa: analysis skipped due to errors in package 
WARN [runner/govet] govet error: nilness: failed prerequisites: buildssa@github.com/MontFerret/ferret/examples 
WARN [runner] Can't run linter govet: asmdecl: analysis skipped due to errors in package 
pkg/runtime/core/errors.go:27:18: `src` can be `fmt.Stringer` (interfacer)
func SourceError(src SourceMap, err error) error {
                 ^
pkg/runtime/values/string.go:120:24: `other` can be `fmt.Stringer` (interfacer)
func (t String) Concat(other core.Value) String {
                       ^
pkg/drivers/cdp/templates/attributes.go:9:20: `name` can be `fmt.Stringer` (interfacer)
func AttributeRead(name values.String) string {
                   ^
pkg/drivers/cdp/templates/styles.go:10:16: `name` can be `fmt.Stringer` (interfacer)
func StyleRead(name values.String) string {
               ^
pkg/drivers/common/styles.go:14:24: `input` can be `fmt.Stringer` (interfacer)
func DeserializeStyles(input values.String) (*values.Object, error) {
                       ^
panic: runtime error: index out of range

goroutine 19316 [running]:
github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers.init.16.func1.1.1(0xc01103e100, 0xc01bfe4b10)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers/dupArg_checker.go:26 +0x8b
github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers.(*dupArgChecker).VisitExpr(0xc01bff44e0, 0x1bd4d60, 0xc01103e100)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-critic/go-critic/checkers/dupArg_checker.go:111 +0xca
github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk.(*exprWalker).WalkFile.func1(0x1bcda20, 0xc01103e100, 0xc010fdb601)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk/expr_walker.go:23 +0x7f
go/ast.inspector.Visit(0xc0352c0770, 0x1bcda20, 0xc01103e100, 0x1bc4780, 0xc0352c0770)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcda20, 0xc01103e100)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:52 +0x66
go/ast.walkExprList(0x1bc4780, 0xc0352c0770, 0xc010f172e0, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcd820, 0xc01103e140)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:207 +0x2103
go/ast.walkStmtList(0x1bc4780, 0xc0352c0770, 0xc010fdb6e0, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcd9a0, 0xc01103c300)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcde60, 0xc010f17330)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:98 +0x2c13
go/ast.walkExprList(0x1bc4780, 0xc0352c0770, 0xc010fdb700, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcda20, 0xc01103e1c0)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:137 +0x107a
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcdce0, 0xc010f17350)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:196 +0x1b12
go/ast.walkStmtList(0x1bc4780, 0xc0352c0770, 0xc010f17360, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcd9a0, 0xc01103c330)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcde60, 0xc010f17370)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:98 +0x2c13
go/ast.walkExprList(0x1bc4780, 0xc0352c0770, 0xc01103e200, 0x3, 0x4)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcda20, 0xc01103e240)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:137 +0x107a
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcdce0, 0xc010f17390)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:196 +0x1b12
go/ast.walkStmtList(0x1bc4780, 0xc0352c0770, 0xc01103f4c0, 0x3, 0x4)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcd9a0, 0xc01103ca20)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x1bc4780, 0xc0352c0770, 0x1bcde20, 0xc01103ca50)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:344 +0xd73
go/ast.Inspect(...)
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/go/ast/walk.go:385
github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk.(*exprWalker).WalkFile(0xc01bfe6f80, 0xc010f90300)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/astwalk/expr_walker.go:21 +0x12d
github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack.(*Checker).Check(...)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/go-lintpack/lintpack/lintpack.go:126
github.com/golangci/golangci-lint/pkg/golinters.Gocritic.runOnFile.func1(0xc0352bcea0, 0xc010f90300, 0xc01bfea870, 0xc01bff8120, 0xc01bfeeac0)
        /home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/gocritic.go:157 +0x8f
created by github.com/golangci/golangci-lint/pkg/golinters.Gocritic.runOnFile
        /home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/gocritic.go:154 +0xa8
```

**Comment by jirfag** [comment]
thank you, I've created https://github.com/go-critic/go-critic/issues/842

**Comment by jirfag** [comment]
Check in master please

**Comment by 3timeslazy** [comment]
It works! Thanks a lot!
