### ISSUE TITLE
Can't run linter golint: panic occurred: runtime error: index out of range 

### ISSUE THREAD

**Issue by dvyukov** [golangci/golangci-lint#466]
I am running the latest version and getting:
```
WARN [runner] Panic stack trace: goroutine 162 [running]:
runtime/debug.Stack(0xd1c4c0, 0xc01448c6e0, 0xc0148fee30)
	/go1.12/src/runtime/debug/stack.go:24 +0x9d
github.com/golangci/golangci-lint/pkg/lint.(*Runner).runLinterSafe.func1(0xc0148ffce8, 0xc0148ffee0)
	/gopath/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:106 +0xfd
panic(0xd03720, 0x16de9c0)
	/go1.12/src/runtime/panic.go:522 +0x1b5
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.srcLine(0xc01edea000, 0x1279, 0x1479, 0xc009eab100, 0x71, 0x17161, 0x75, 0x0, 0x8140b1, 0xc009c72960)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:1705 +0xf3
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*pkg).errorfAt(0xc01b589ae0, 0xc009eab100, 0x71, 0x17161, 0x75, 0x0, 0x3ff0000000000000, 0xc0148ff1c8, 0x5, 0x5, ...)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:279 +0x38d
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*file).errorf(0xc01cca6cc0, 0xfd04c0, 0xc00c484120, 0x3ff0000000000000, 0xc0148ff1c8, 0x5, 0x5, 0xc01228d600)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:268 +0x16b
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*file).lintFuncDoc(0xc01cca6cc0, 0xc00c484120)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:894 +0x442
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*file).lintExported.func1(0xfd04c0, 0xc00c484120, 0xfd0b00)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:545 +0xdc
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.walker.Visit(0xc010f8dc20, 0xfd04c0, 0xc00c484120, 0x0, 0x0)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:1590 +0x3a
go/ast.Walk(0xfc6b80, 0xc010f8dc20, 0xfd04c0, 0xc00c484120)
	/go1.12/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0xfc6b80, 0xc010f8dc20, 0xc012462400, 0xb, 0x10)
	/go1.12/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0xfc6b80, 0xc010f8dc20, 0xfd0440, 0xc0133d5280)
	/go1.12/src/go/ast/walk.go:353 +0x2659
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*file).walk(...)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:1566
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*file).lintExported(0xc01cca6cc0)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:535 +0xfc
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*file).lint(0xc01cca6cc0)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:240 +0x59
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*pkg).lint(0xc01b589ae0, 0xc01ccb20c0, 0xc009eab280, 0x73)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:217 +0xc7
github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1.(*Linter).LintASTFiles(0xc0148ff990, 0xc01cca6c40, 0x5, 0x8, 0xc009d6aa80, 0x5, 0xc01cca6c40, 0x4, 0x8, 0xc009eab280)
	/gopath/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/lint-1/lint.go:156 +0x7f0
github.com/golangci/golangci-lint/pkg/golinters.Golint.lintPkg(0x3fe999999999999a, 0xc01cca6c40, 0x5, 0x8, 0xc009d6aa80, 0xc009d6aa80, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:50 +0x74
github.com/golangci/golangci-lint/pkg/golinters.Golint.Run(0xfdbd60, 0xc000125a40, 0xc00c69c000, 0xc010b9b310, 0x1, 0x1, 0xfe2c00, 0xc00c5b9b00)
	/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:34 +0x130
github.com/golangci/golangci-lint/pkg/lint.(*Runner).runLinterSafe(0xc00010bee0, 0xfdbd60, 0xc000125a40, 0xc000316000, 0xc00020cd00, 0x0, 0x0, 0x0, 0xfc5480, 0xc01448c6e0)
	/gopath/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:112 +0x16a
github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker.func1()
	/gopath/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:146 +0x64
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc00c694000, 0xdfc76c, 0x6, 0xc00010be40)
	/gopath/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:75 +0x50
github.com/golangci/golangci-lint/pkg/lint.Runner.runWorker(0xc000158240, 0x11, 0x11, 0xfe5d20, 0xc00c5b1f50, 0xfdbd60, 0xc000125a40, 0xc000316000, 0xc00c5d1140, 0xc00c5d11a0, ...)
	/gopath/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:145 +0x23b
github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers.func1(0xc00c61dcc0, 0xc00c5cfda0, 0xfdbd60, 0xc000125a40, 0xc000316000, 0xc00c5d1140, 0xc00c5d11a0, 0xc000c74300, 0x48, 0x48, ...)
	/gopath/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:200 +0x163
created by github.com/golangci/golangci-lint/pkg/lint.(*Runner).runWorkers
	/gopath/src/github.com/golangci/golangci-lint/pkg/lint/runner.go:197 +0x1ab
 
WARN [runner] Can't run linter golint: panic occurred: runtime error: index out of range 
```

Here is the additional info:
https://gist.githubusercontent.com/dvyukov/477e67ca9b376dafbcfca30f88d2a319/raw/17b19a5d0a6e3356da476be1a9465949625c002c/gistfile1.txt

**Comment by jirfag** [comment]
Hi, thank you!
The issue was because of poor `.rl` and `.y` files support. I've fixed it in https://github.com/golangci/golangci-lint/pull/504 and https://github.com/golangci/golangci-lint/pull/505.
I've run `golangci-lint` on the github.com/google/syzkaller: it works ok now for me.

**Comment by dvyukov** [comment]
Now everything seems to work as expected. Thanks!
