### ISSUE TITLE
Another nil dereference

### ISSUE THREAD

**Issue by leakingtapan** [golangci/golangci-lint#631]
I saw there are several NPE already, since mine is a bit different to the previous ones, hence creating a new issue:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x163f39c]

goroutine 13135 [running]:
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*fnVisitor).Visit(0xc05e4ba880, 0x1a30c80, 0xc01ca08870, 0x100ba18, 0x17c5d40)
        /Users/chengpan/workspace/csi-ebs/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:837 +0x39c
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.(*globalVisitor).Visit(0xc05e4ba860, 0x1a30c80, 0xc01ca08870, 0x1a2d160, 0xc05e4ba860)
        /Users/chengpan/workspace/csi-ebs/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:820 +0xc2
go/ast.Walk(0x1a2d160, 0xc05e4ba860, 0x1a30c80, 0xc01ca08870)
        /usr/local/Cellar/go/1.11/libexec/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x1a2d160, 0xc05e4ba860, 0xc0268f7460, 0x2, 0x2)
        /usr/local/Cellar/go/1.11/libexec/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0x1a2d160, 0xc05e4ba860, 0x1a30c00, 0xc02ad87980)
        /usr/local/Cellar/go/1.11/libexec/src/go/ast/walk.go:353 +0x2656
github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.NodeFns.func1(0xc05d8e7080, 0xc05dfb39e0, 0xc05e3759b0)
        /Users/chengpan/workspace/csi-ebs/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:787 +0x74
created by github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint.NodeFns
        /Users/chengpan/workspace/csi-ebs/src/github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint/lint.go:784 +0xe7
make: *** [verify] Error 2
```

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
this `--version` is not available

2. Config file: `cat .golangci.yml`

3. Go environment: `go version && go env`
```
go version go1.12.5 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chengpan/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chengpan/workspace/csi-ebs"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xn/2l8v63ss6gddykbkjrjdfsfdpm_d3c/T/go-build833960114=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

4. Verbose output of running: `golangci-lint run -v`

**Comment by jirfag** [comment]
Hi, staticcheck was updated, a lot of base code reworked. Should have been fixed
