### ISSUE TITLE
v1.19.1 and v1.20.0/ interface conversion: *ssa.Call is not interface

### ISSUE THREAD

**Issue by alexec** [golangci/golangci-lint#802]
Thank you for creating the issue!

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution) v1.19.1 and v0.20
```
golangci-lint has version v1.19.1 built from (unknown, mod sum: "h1:g9xL8KW7UZDCkVlgHYJMA6F4Sj/sRVa0FoCeXI+Z3iM=") on (unknown)
```
2. Config file: `cat .golangci.yml`
```
run:
  deadline: 2m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs:
    - pkg/client
    - vendor
linters:
  enable:
    - vet
    - deadcode
    - varcheck
    - structcheck
    - ineffassign
    - unconvert
    - unparam
```
3. Go environment: `go version && go env`
```
$ go version && go env
go version go1.12.10 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/acollins8/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/acollins8/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go@1.12/1.12.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.12/1.12.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v5/0lllbd_s0ldg1dr4qxm7vw0scm2ffd/T/go-build234809910=/tmp/go-build -gno-record-gcc-switches -fno-common"

```
4. Verbose output of running: `golangci-lint run -v`
```
GOGC=off golangci-lint run --fix --verbose --concurrency 8 --deadline 1m0s
INFO [config_reader] Config search paths: [./ /Users/acollins8/go/src/github.com/argoproj/argo-cd /Users/acollins8/go/src/github.com/argoproj /Users/acollins8/go/src/github.com /Users/acollins8/go/src /Users/acollins8/go /Users/acollins8 /Users /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 12 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unconvert unparam unused varcheck] 
INFO [lintersdb] Optimized sublinters [staticcheck gosimple unused] into metalinter megacheck 
INFO [loader] Go packages loading at mode 1023 (types|types_info|deps|files|name|syntax|compiled_files|exports_file|imports|types_sizes) took 6.997242291s 
INFO [loader] SSA repr building timing: packages building 60.635218ms, total 881.703324ms 
INFO [runner] worker.7 took 66.667324ms with stages: structcheck: 66.598712ms 
INFO [runner] worker.1 took 84.322045ms with stages: errcheck: 47.788729ms, unconvert: 36.229504ms, typecheck: 248.476µs 
INFO [runner] worker.4 took 110.800615ms with stages: deadcode: 110.790994ms 
INFO [runner] worker.8 took 227.521462ms with stages: varcheck: 227.497631ms 
INFO [runner] worker.3 took 1.294161825s with stages: ineffassign: 1.294134798s 
INFO [runner] worker.5 took 1.333695317s with stages: unparam: 1.333653688s 
WARN [linters context] Panic: buildssa: package "common" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: *ssa.Call is not interface { ssa.setNum(int) }: missing method setNum: goroutine 31074 [running]:
runtime/debug.Stack(0x1b6b079, 0x3c, 0xc0a2817078)
	/usr/local/Cellar/go@1.12/1.12.10/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1(0xc0a1f88c00)
	/Users/acollins8/go/pkg/mod/github.com/golangci/golangci-lint@v1.19.1/pkg/golinters/goanalysis/runner.go:404 +0x1af
panic(0x19c0560, 0xc0a727c540)
	/usr/local/Cellar/go@1.12/1.12.10/libexec/src/runtime/panic.go:522 +0x1b5
honnef.co/go/tools/ssa.numberRegisters(0xc0a72648c0)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/func.go:278 +0x114
honnef.co/go/tools/ssa.(*Function).finishBody(0xc0a72648c0)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/func.go:410 +0x746
honnef.co/go/tools/ssa.makeWrapper(0xc0a6298c80, 0xc0a582f810, 0x0)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/wrappers.go:135 +0x70a
honnef.co/go/tools/ssa.(*Program).addMethod(0xc0a6298c80, 0xc0a6bd3ad0, 0xc0a582f810, 0xc0a6bd3ad0)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:84 +0x13f
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0a6298c80, 0x1cc1320, 0xc0a6bd3ac0, 0xc0a7264600)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:173 +0x853
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0a6298c80, 0x1cc12a0, 0xc01746d920, 0x24f1500)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:215 +0x72c
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0a6298c80, 0x1cc1420, 0xc017537da0, 0x24f1500)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:233 +0x2a6
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0a6298c80, 0x1cc1360, 0xc01746da70, 0x0)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:210 +0x619
honnef.co/go/tools/ssa.(*Program).needMethodsOf(0xc0a6298c80, 0x1cc1360, 0xc01746da70)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:145 +0x5d
honnef.co/go/tools/ssa.(*Package).build(0xc0a43f7f80)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/builder.go:2272 +0x110
sync.(*Once).Do(0xc0a43f7fac, 0xc0a1d97c70)
	/usr/local/Cellar/go@1.12/1.12.10/libexec/src/sync/once.go:44 +0xb3
honnef.co/go/tools/ssa.(*Package).Build(0xc0a43f7f80)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/builder.go:2260 +0x54
honnef.co/go/tools/internal/passes/buildssa.run(0xc0a6298be0, 0x1e09eff5d, 0x24f25c0, 0x2, 0x2)
	/Users/acollins8/go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/internal/passes/buildssa/buildssa.go:70 +0x27b
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc0a1f88c00)
	/Users/acollins8/go/pkg/mod/github.com/golangci/golangci-lint@v1.19.1/pkg/golinters/goanalysis/runner.go:495 +0x85b
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc0a1f88c00)
	/Users/acollins8/go/pkg/mod/github.com/golangci/golangci-lint@v1.19.1/pkg/golinters/goanalysis/runner.go:407 +0x51
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func3(0xc0a5e6b590, 0xc0a1f88c00)
	/Users/acollins8/go/pkg/mod/github.com/golangci/golangci-lint@v1.19.1/pkg/golinters/goanalysis/runner.go:961 +0x5f
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/Users/acollins8/go/pkg/mod/github.com/golangci/golangci-lint@v1.19.1/pkg/golinters/goanalysis/runner.go:956 +0x2cd 
INFO [runner] worker.6 took 2.038513439s with stages: megacheck: 2.038507059s 
INFO [runner] worker.2 took 2.164348275s with stages: govet: 2.164313023s 
INFO [runner] Workers idle times: #1: 2.079796093s, #3: 870.145376ms, #4: 2.043953895s, #5: 830.426001ms, #6: 125.406911ms, #7: 2.096108408s, #8: 1.936609706s 
INFO [runner/skip dirs] Skipped 2 issues from dir pkg/client/clientset/versioned/fake by pattern pkg/client 
INFO [runner] Issues before processing: 72, after processing: 0 
INFO [runner] Processors filtering stat (out/in): cgo: 72/72, path_prettifier: 72/72, skip_files: 42/72, skip_dirs: 40/42, identifier_marker: 8/8, filename_unadjuster: 72/72, autogenerated_exclude: 8/40, exclude: 0/8 
INFO [runner] processing took 12.893588ms with stages: skip_dirs: 10.158526ms, autogenerated_exclude: 1.412582ms, exclude: 557.434µs, identifier_marker: 268.034µs, skip_files: 241.56µs, path_prettifier: 135.511µs, cgo: 79.974µs, filename_unadjuster: 23.888µs, nolint: 2.318µs, diff: 2.178µs, max_from_linter: 1.927µs, max_same_issues: 1.894µs, path_shortener: 1.837µs, source_code: 1.807µs, exclude-rules: 1.544µs, uniq_by_line: 1.407µs, max_per_file_from_linter: 1.167µs 
INFO fixer took 0s with no stages                 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 102 samples, avg is 1442.8MB, max is 5432.0MB 
INFO Execution took 10.07766155s     
```

**Comment by jirfag** [comment]
Please, use binary release (preferred) or go >= 1.13

**Comment by tpounds** [comment]
@alexec To provide some context here are some of the Go issues related to this problem.

https://github.com/golang/go/issues/29612
https://github.com/golang/tools/pull/162
