### ISSUE TITLE
linter gosimple produce panic

### ISSUE THREAD

**Issue by ManuelReschke** [golangci/golangci-lint#816]
ERROR:
golangci-lint run --config .golangci.yaml
WARN [linters context] Panic: buildssa: package "models" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: *ssa.Call is not interface { ssa.setNum(int) }: missing method setNum: goroutine 2672 [running]:

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
# golangci-lint has version v1.20.0
```

</details>

<details><summary>Config file</summary>

```bash
$ cat .golangci.yml
# # This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # default concurrency is a available CPU number
  #concurrency: 2

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 30m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - mytag

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - api/rest
    - pkg/restapi
    - src/external_libs
    - autogenerated_by_my_lib
    - pkg/provider/hlx

  # which files to skip: they will be analyzed, but issues from them
  # won't be reported. Default value is empty list, but there is
  # no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
  skip-files:
    - test/add_transfer_test.go
    - pkg/soap/client.go
    - pkg/midi/params.go #need to ignored because there is a spelling problem in the request

  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #modules-download-mode: readonly|release|vendor


# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  enable:
      - bodyclose #checks whether HTTP response body is closed successfully [fast: true, auto-fix: false]
      - deadcode #Finds unused code [fast: true, auto-fix: false]
      - depguard #Go linter that checks if package imports are in a list of acceptable packages [fast: true, auto-fix: false]
      - dogsled #Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()) [fast: true, auto-fix: false]
      - dupl #Tool for code clone detection [fast: true, auto-fix: false]
      - errcheck #Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases [fast: true, auto-fix: false]
      - funlen #Tool for detection of long functions [fast: true, auto-fix: false]
      - gochecknoglobals #Checks that no globals are present in Go code [fast: true, auto-fix: false]
      - gochecknoinits #Checks that no init functions are present in Go code [fast: true, auto-fix: false]
      - gocognit #Computes and checks the cognitive complexity of functions [fast: true, auto-fix: false]
      - goconst #Finds repeated strings that could be replaced by a constant [fast: true, auto-fix: false]
      - gocritic #The most opinionated Go source code linter [fast: true, auto-fix: false]
      - gocyclo #Computes and checks the cyclomatic complexity of functions [fast: true, auto-fix: false]
#      - godox #Tool for detection of FIXME, TODO and other comment keywords [fast: true, auto-fix: false]
      - gofmt #Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification [fast: true, auto-fix: true]
      - goimports #Goimports does everything that gofmt does. Additionally it checks unused imports [fast: true, auto-fix: true]
      - golint #Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes [fast: true, auto-fix: false]
      - gosimple #(megacheck): Linter for Go source code that specializes in simplifying a code [fast #true, auto-fix: false]
  #    - govet #(vet, vetshadow): Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string [fast: true, auto-fix: false]
  #    - ineffassign # Detects when assignments to existing variables are not used [fast: true, auto-fix: false]
  #    - interfacer # Linter that suggests narrower interface types [fast: true, auto-fix: false]
  #    - lll # Reports long lines [fast: true, auto-fix: false]
  #    - maligned # Tool to detect Go structs that would take less memory if their fields were sorted [fast: true, auto-fix: false]
  #    - misspell # Finds commonly misspelled English words in comments [fast: true, auto-fix: true]
  #    - nakedret # Finds naked returns in functions greater than a specified function length [fast: true, auto-fix: false]
  #    - prealloc # Finds slice declarations that could potentially be preallocated [fast: true, auto-fix: false]
  #    - scopelint # Scopelint checks for unpinned variables in go programs [fast: true, auto-fix: false]
  #    - staticcheck # (megacheck): Staticcheck is a go vet on steroids, applying a ton of static analysis checks [fast: true, auto-fix: false]
  #    - structcheck # Finds unused struct fields [fast: true, auto-fix: false]
  #    - stylecheck # Stylecheck is a replacement for golint [fast: true, auto-fix: false]
  #    - typecheck # Like the front-end of a Go compiler, parses and type-checks Go code [fast: true, auto-fix: false]
  #    - unconvert # Remove unnecessary type conversions [fast: true, auto-fix: false]
  #    - unparam # Reports unused function parameters [fast: true, auto-fix: false]
  #    - varcheck # Finds unused global variables and constants [fast: true, auto-fix: false]
  #    - whitespace # Tool for detection of leading and trailing whitespace [fast: true, auto-fix: true]
  #    - wsl # Whitespace Linter - Forces you to use empty lines! [fast: true, auto-fix: false]
  #    - gosec #(gas): Inspects source code for security problems [fast: true, auto-fix: false]
  #    - unused #(megacheck): Checks Go code for unused constants, variables, functions and types [fast: false, auto-fix: false]
  enable-all: false
  #disable:
  disable-all: true
  fast: false


# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false

    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    # see https://github.com/kisielk/errcheck#the-deprecated-method for details
    ignore: fmt:.*,io/ioutil:^Read.*,io:^Close

    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    #exclude: /path/to/file.txt

  funlen:
    lines: 100
    statements: 50

  govet:
    # report about shadowed variables
    check-shadowing: false

    # settings per analyzer
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/org/project
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 150
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/davecgh/go-spew/spew
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - someword
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1
  unused:
    # treat code as a program (not a library) and report unused exported identifiers; default is false.
    # XXX: if you enable this setting, unused will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find funcs usages. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: true
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 30
  prealloc:
    # XXX: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.

    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default
  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    enabled-checks:
      #- rangeValCopy

    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust

    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint` run to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - performance

    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude:
    - abcdef

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known linters from partially hard-vendored code,
    # which is impossible to exclude via "nolint" comments.
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing
  # large codebase. It's not practical to fix all existing issues at the moment
  # of integration: much better don't allow issues in new code.
  # Default is false.
  new: false

  # Show only new issues created after git revision `REV`
  #new-from-rev: REV

  # Show only new issues created in git patch with set file path.
  #new-from-patch: path/to/patch/file
```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
# go version go1.12.10 linux/amd64
```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
# INFO [config_reader] Config search paths: [./ /home/m.reschke/Workspace/GitlabWork/checkoutsvc-v1 /home/m.reschke/Workspace/GitlabWork /home/m.reschke/Workspace /home/m.reschke /home /] 
INFO [config_reader] Used config file .golangci.yaml 
INFO [lintersdb] Active 17 linters: [bodyclose deadcode depguard dogsled dupl errcheck funlen gochecknoglobals gochecknoinits gocognit goconst gocritic gocyclo gofmt goimports golint gosimple] 
INFO [loader] Go packages loading at mode 575 (deps|compiled_files|exports_file|files|imports|name|types_sizes) took 354.078077ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 15.315986ms 
WARN [linters context] Panic: buildssa: package "models" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: *ssa.Call is not interface { ssa.setNum(int) }: missing method setNum: goroutine 2970 [running]:
runtime/debug.Stack(0xf7d4a9, 0x3c, 0xc000e02c28)
        /home/m.reschke/.local/share/golang/src/runtime/debug/stack.go:24 +0x9d
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1(0xc0015493d0)
        /home/m.reschke/Workspace/Go/pkg/mod/github.com/golangci/golangci-lint@v1.20.0/pkg/golinters/goanalysis/runner.go:473 +0x1b5
panic(0xdd3460, 0xc00698b230)
        /home/m.reschke/.local/share/golang/src/runtime/panic.go:522 +0x1b5
honnef.co/go/tools/ssa.numberRegisters(0xc007e01040)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/func.go:278 +0x114
honnef.co/go/tools/ssa.(*Function).finishBody(0xc007e01040)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/func.go:410 +0x746
honnef.co/go/tools/ssa.makeWrapper(0xc0049c5ea0, 0xc007e02c30, 0x0)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/wrappers.go:135 +0x70a
honnef.co/go/tools/ssa.(*Program).addMethod(0xc0049c5ea0, 0xc004429360, 0xc007e02c30, 0xc004429360)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:84 +0x13f
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5780, 0xc004429320, 0xc00488a500)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:173 +0x853
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5700, 0xc000405e00, 0x1905d00)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:215 +0x72c
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5880, 0xc000ee5360, 0xc006db5400)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:233 +0x2a6
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5700, 0xc000665ef0, 0x1905d00)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:182 +0x1ac
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5880, 0xc0020f3f40, 0xc006db5100)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:233 +0x2a6
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5700, 0xc0021f6cf0, 0x1905d00)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:182 +0x1ac
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5880, 0xc0075d3cc0, 0xc007dfed00)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:233 +0x2a6
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5780, 0xc004429180, 0xc006db4e00)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:181 +0x178
honnef.co/go/tools/ssa.(*Program).needMethods(0xc0049c5ea0, 0x10d5700, 0xc00381d4a0, 0x0)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:215 +0x72c
honnef.co/go/tools/ssa.(*Program).needMethodsOf(0xc0049c5ea0, 0x10d5700, 0xc00381d4a0)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/methods.go:145 +0x5d
honnef.co/go/tools/ssa.(*Package).build(0xc001314900)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/builder.go:2272 +0x110
sync.(*Once).Do(0xc00131492c, 0xc000e03c80)
        /home/m.reschke/.local/share/golang/src/sync/once.go:44 +0xb3
honnef.co/go/tools/ssa.(*Package).Build(0xc001314900)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/ssa/builder.go:2260 +0x54
honnef.co/go/tools/internal/passes/buildssa.run(0xc0049c5e00, 0x3958b0b4, 0x1906de0, 0x2, 0x2)
        /home/m.reschke/Workspace/Go/pkg/mod/honnef.co/go/tools@v0.0.1-2019.2.3/internal/passes/buildssa/buildssa.go:70 +0x27b
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc0015493d0)
        /home/m.reschke/Workspace/Go/pkg/mod/github.com/golangci/golangci-lint@v1.20.0/pkg/golinters/goanalysis/runner.go:564 +0x9e8
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc0015493d0)
        /home/m.reschke/Workspace/Go/pkg/mod/github.com/golangci/golangci-lint@v1.20.0/pkg/golinters/goanalysis/runner.go:476 +0x51
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func3(0xc009534bc0, 0xc0015493d0)
        /home/m.reschke/Workspace/Go/pkg/mod/github.com/golangci/golangci-lint@v1.20.0/pkg/golinters/goanalysis/runner.go:1030 +0x5f
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        /home/m.reschke/Workspace/Go/pkg/mod/github.com/golangci/golangci-lint@v1.20.0/pkg/golinters/goanalysis/runner.go:1025 +0x2cf 
INFO [runner] processing took 2.491µs with stages: max_same_issues: 614ns, skip_dirs: 337ns, max_from_linter: 200ns, nolint: 157ns, cgo: 147ns, path_prettifier: 130ns, autogenerated_exclude: 128ns, filename_unadjuster: 127ns, skip_files: 120ns, diff: 111ns, identifier_marker: 96ns, path_shortener: 64ns, source_code: 57ns, exclude-rules: 56ns, max_per_file_from_linter: 50ns, uniq_by_line: 49ns, exclude: 48ns 
INFO [runner] linters took 1.069591573s with stages: goanalysis_metalinter: 1.069552494s 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 16 samples, avg is 148.5MB, max is 203.6MB 
INFO Execution took 1.447830593s 
```

</details>

**Comment by jirfag** [comment]
Hi, the answer is in deleted issue block:

- [ ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

--
Just use binary release.
